### ISSUE TITLE
One Tasker

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#114]
- [x] Add One Tasker dashboard (pulling all onetasker events for the current user)
- [x] Add One Tasker hub (where user can see info about a task and accept or decline it)
- [x] Add One Tasker about (where user can see SOME info about the project/book)
- [x] Add One Tasker accept (where if the user has accepted the task, they can do it!)
- [x] Add One Tasker complete (where the user can see their completed entry)
- [x] On decline, add a notification to the requesting Editor

**Comment by mauromsl** [comment]
|  (where user can see SOME info about the project/book)

SOME doesn't tell much
