### ISSUE TITLE
Reviewer Workflow

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#116]
Current reviewer workflow isn't great. 

- [x] Copy the onetasker dash and make a new reviewer dash. It should show all outstanding review requests that are not completed for a user. That should link through to either: the "Accept/Decline page" if not accepted or declined, the "Accepted" page if accepted or the "Completed page if completed"
- [x] Add a hub page where the user can accept or decline a review
- [x] Add an Accepted page where the user can undertake the review
- [x] Add a Completed page where the user can view their completed review
- [x] If a review is declined, it should no longer show up for the reviewer, and a Notification should be added to the requesting editor
- [x] Copy ajax from user home for tasks to editor dashboard for notifications. function task_complete in core 
- [x] Add log messages
- [x] Contact editor split to individual. if series editor - different color
- [x] Clear up string concatenation into String Formatting using "something %s something" % variable
- [x] Move Accept/Decline page into its own view
- [x] Move style tags to classes

**Comment by ajrbyers** [comment]
@IoannisCleary is this now complete?

**Comment by IoannisCleary** [comment]
@ajrbyers  yes
