### ISSUE TITLE
Editor Workflow

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#118]
- [x] Add Editor Dashboard
- [x] Add Project Detail
- [x] Add Current Status
- [x] Add Review Pages
- [x] Add Editing Page
- [x] Add Copyediting Pages
- [x] Add Indexing Pages
- [x] Add Production Page
- [x] Add Format/Chapter Pages
- [x] Add Typesetter Pages
- [x] Add Catalogue Pages
- [x] Add Contract Management Pages
- [x] Add Misc Files pages
- [x] Add Revisions pages

**Comment by ajrbyers** [comment]
@IoannisCleary: can you do the Contract Management pages next? Entry point is the bottom right hand of the Editor "submission details" page.

**Comment by IoannisCleary** [comment]
@ajrbyers  okay

**Comment by ajrbyers** [comment]
Catalog is now complete. Moving on to Revisions.

**Comment by ajrbyers** [comment]
Revisions pages also now complete.

**Comment by IoannisCleary** [comment]
Contract pages for the most part are done. Should I close the issue ?
