### ISSUE TITLE
Workflow to Core

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#119]
There are a few functions we need to move from Workflow to Core.

- [x] Serve File
- [x] Update File
- [x] Delete File
- [x] File Versions
- [x] Server Versioned File
- [x] Misc Files

Each page should have a design inspired by the new workflow stuff.

View, Template and URL already exist and simple need to be moved.

The URL should have file/ appended to the front of it!

**Comment by ajrbyers** [comment]
Following error when attempting to add a misc file:

AttributeError at /misc_files/28/upload/
'module' object has no attribute 'UploadMiscFile'

**Comment by IoannisCleary** [comment]
I didn't move the form from Workflow. Committing the change now
