### ISSUE TITLE
Decomission Workflow App

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#120]
We need to decommission this app. Which means:

- [x] Migrate any workflow models to Core
- [x] Migrate any logic to a more appropriate Logic file or, if shared, Core
- [x] Migrate any forms to a more appropriate Forms file or, if shared, Core
- [x] Ensure all views have coverage elsewhere
- [x] Update any places using workflow_logic to pull the new place

Perhaps best to record where a function is being moved to so that we can track.

**Comment by IoannisCleary** [comment]
Have a look and see if anything breaks before I close the issue. (I tested all dashboards and most pages and it didn't break)

**Comment by ajrbyers** [comment]
Having had a look through the system thus far I'm happy with the destruction of the evil workflow app. Good work @IoannisCleary.
