### ISSUE TITLE
Decomission Indexing/Copyediting/Typeset Apps

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#121]
We need to decommission this app. Which means:

### Indexing
- [x] Migrate any workflow models to Core
- [x] Migrate any logic to a more appropriate Logic file or, if shared, Core
- [x] Migrate any forms to a more appropriate Forms file or, if shared, Core
- [x] Ensure all views have coverage elsewhere
- [x] Update any places using workflow_logic to pull the new place

### Copyediting
- [x] Migrate any workflow models to Core
- [x] Migrate any logic to a more appropriate Logic file or, if shared, Core
- [x] Migrate any forms to a more appropriate Forms file or, if shared, Core
- [x] Ensure all views have coverage elsewhere
- [x] Update any places using workflow_logic to pull the new place

### Typeset
- [x] Migrate any workflow models to Core
- [x] Migrate any logic to a more appropriate Logic file or, if shared, Core
- [x] Migrate any forms to a more appropriate Forms file or, if shared, Core
- [x] Ensure all views have coverage elsewhere
- [x] Update any places using workflow_logic to pull the new place

Perhaps best to record where a function is being moved to so that we can track.

**Comment by IoannisCleary** [comment]
Home url for 'copyedit' view removed
