### ISSUE TITLE
Lots of Template Vars not required

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#160]
```
		'editor_submission': True,
		'my_tasks': False,
		'editor_review': False,
		'editing': False ,
		'catalog_view':False,
		'production': False,
		'status': False ,
```

Rather than this, we should have a single variable:

active_page = 'editor_submission'

**Comment by IoannisCleary** [comment]
I just removed the false variables so that the templates stay the same

**Comment by IoannisCleary** [comment]
Since they all use the a main template

**Comment by IoannisCleary** [comment]
Updated the views and templates to use the 'active_page' tag
