### ISSUE TITLE
Ability to assign Editors

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#171]
We need to have the ability to assign specific editors/Editorial Managers to look after the book publications - e.g. for UP we have 5 EMs currently looking after their own projects. This should be don-able once the submission is received, but also changable through the process (in case someone leaves, workload changes etc)

- [x] Editor: submission details add Editor section above authors. editor names + add editor button
- [x] Add editor page on the right + email template

**Comment by ajrbyers** [comment]
- [ ] Allow Press Editor to assign editors
- [ ] Allow Press Editor to un-assign editors
- [ ] Display editors on the submission sidebars.
