### ISSUE TITLE
Principal Contact

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#172]
We need to setup a principal contact setting (one for name, one for email).

**Comment by twakeford** [comment]
After quick discussion with Andy, agreed for enhancement to allow the contact author to be changed during the submission/editorial process:

"If someone is set to be the Primary Contact they should have an account generated and allow them to login and muck about with the backend"

The editor should be able to change the Primary Contact at any point.

**Comment by IoannisCleary** [comment]
@ajrbyers  @twakeford  I'll add a set primary contact page with a list of existing users where you can select the primary contact  (this will update the primary contact settings) + a button so that you can create a new user

**Comment by ajrbyers** [comment]
We should chat about this one tomorrow

Andy Byers
Technical Architect, Ubiquity Press

**Comment by twakeford** [comment]
Yeah - when changing the Corresponding author then they are unlikely to be already registered, but their main details will already have been added in the contributor section....discussion tomorrow sounds good

**Comment by ajrbyers** [comment]
- [ ] Add new manytomany field read_only_users
- [ ] Allow New "change owner" page
- [ ] Display datatable of existing users (with author role), allow user to select one
- [ ] Display datatable of current Book.Authors or Book.Editors, allow user to select one
- [ ] If user selects an existing user, move the current owner to read_only_users, move selected user to owner
- [ ] If user selects an author, create a User and Profile object for the user, create a reset code and send an email with the username and reset code to the user

**Comment by IoannisCleary** [comment]
- [ ] Update book.authors to User model
- [ ] Update references to book.authors

**Comment by IoannisCleary** [comment]
8d20dc1b4a13fc259e744fdd2d7074cc996fa3ed Updated book attribute authors to User model + updated most references if not all to author in other views and templates

**Comment by IoannisCleary** [comment]
- [ ] If editor or author profile/user already exists then assign that instead of creating a new one
