### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#184]
- [x] Only record the actual recipient, not the list for emails
- [x] Remove file download log item
- [ ] When a user makes revisions, log should read Uploaded not Downloaded

**Comment by ajrbyers** [comment]
Email logging currently stored the list ie. ['andy.byers@ubiquitypress.com'] but we only want the strings.

**Comment by IoannisCleary** [comment]
@ajrbyers I can find log entries that say revisions submitted or requested (editor) not downloaded.
File download log : Remove the add to log lines for file downloads ?
