### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#185]
- [x] Allow user to request a reset code
- [x] Link to update password page

**Comment by ajrbyers** [comment]
Can you explain the working you've done for this issue? It doesn't look right to me.

Andy Byers
Technical Architect, Ubiquity Press

**Comment by ajrbyers** [comment]
flow should be:

I authenticated user requests a code.

Code is generated and a like is emailed, like will have a get parameter with the code

User clicks the link

System finds the user based on request.Get.get("code")

Presents a password reset page

Password is updated and the code deleted from the Db so it can't be reused.

**Comment by ajrbyers** [comment]
That should be an unauthenticated user requests a code.

**Comment by ajrbyers** [comment]
The code should be a uuid4 so that it is unique.

**Comment by IoannisCleary** [comment]
@ajrbyers 
Resetting your password has 3 stages:
1 - Request a reset code by entering your username ( if it is  a valid username the reset code and link to reset page step 2 is sent to the user's email) :: Reset code is stored in the user profile
2 - Reset code page where you enter the reset code ( if it is valid it redirects to the password reset for unauth) (If a reset code does not exist then page cannot be viewed as a code was not requested)
3 - Reset password page : enter new password twice (if reset code validation is successful you can view this page). (if password validation is correct then the reset code fields are restored to default state (code : None + validated : False).
