### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#186]
- [x] Update CC licenses so the CC BY is the default and only license
- [x] Reviewer suggestions should be Suggested Reviewers
- [x] Editors should be able to disable suggested reviewers
- [x] Add new setting suggested_reviewers_guide and display it on the submission page
- [x] Drop "additional information" text from submission stage 3 in favor of manuscript_guidelines setting
- [x] Add additional_files_guidelines setting to stage 4
- [x] Display file labels on stage 6
- [x] Change subjects to disciplines
- [x] After file upload, display the original file name
- [x] Add note that the first author will be the corresponding author

**Comment by IoannisCleary** [comment]
@ajrbyers  " Change subjects to disciplines " - which page is this bullet point referring to?
"Add new page competing-interests and link to it from the CI help text" : What should this page contain, text area - page with a form or just  competing interests in a box (readonly) ?

**Comment by ajrbyers** [comment]
1. Anywhere "subjects" is displayed most likely the Catalog page.
2. Spin this off onto it's own issue
