### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#191]
- [x] When adding a new reviewer, link to the add user page
- [x] Reviewer invitation page: Add new setting so that a press can enable or disable preview of files before decision.
- [x] Review Decision page should display the abstract
- [x] CI should be mandatory
- [x] Need to highlight on the dashboard/tasks that a review has been completed. Currently RUA doesn't appear to announce to an editor that the reviews have been received unless the editor checks. They need to have a prompt.

**Comment by twakeford** [comment]
Top point related to #218

**Comment by IoannisCleary** [comment]
e11451441f90a9d6550559e78dc4b1e5c9321f05 Editor notification added for review assignment completion
