### ISSUE TITLE
Editorial decision emails

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#194]
When an editorial decision is made to reject the paper the editor does not get the opportunity to see the email template notifying the author and edit it. It is essential that all editorial decisions (send to review, accept and send to production, reject) have an editable email that the editor sees prior to the email being sent (I thought that there is something similar already logged, but can't find it).

**Comment by IoannisCleary** [comment]
We need this to work for all decisions. See attached for plan.

![img_0148](https://cloud.githubusercontent.com/assets/5523178/11714122/cd152506-9f2f-11e5-896e-be7aeb88b2bc.JPG)

**Comment by IoannisCleary** [comment]
Commits:
d44dcdfa037621924cf0b3ddb8bd3fa13bcc289d
99cafbd125cd20558320df6d8e40115e7be3fecc
