### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#201]
- [x] If a task is declined, allow the tasker to email the assigning editor to tell them why. 
- [x] Replace the single file upload field with the submission multi upload system so they can submit multiple files AND add labels *before* completing their task.

**Comment by IoannisCleary** [comment]
Multiple files can be uploaded already in onetasker assignment page. label text fields appear after you submit the assignment

**Comment by ajrbyers** [comment]
Requirements for this issue are clearly outlined. I want the multiple upload system from the Book Submission stages. This will allow them to add labels BEFORE submitting.

We can go over this tomorrow as well.
