### ISSUE TITLE
Copyediting

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#202]
- [x] Copyeditors should only be able to see the original cover letter and suggested reviewers
- [x] Add Notes field for the editor to provide notes to the copyeditor (model attr should already exist...)
- [x] Make it clear that the notes field is the only place a copyeditor will be able to give notes on the edit.....
- [x] The editor should have the option to over-write the copyeditted files before sending them to the Author.
- [x] the copyediting (and possibly other) line of events in the editor view is a little confusing when complete, as the 'due' date and 'Assignment complete' events remain, even after the 'Completed' event is logged. Should these two events be removed one the whole process has been completed? (see screen shot 'copyediting events')

**Comment by twakeford** [comment]
I just tested the copyediting section and the 'copyeditor' provided notes back to the editor prior to completing their task. When the editor logs in then these notes do not appear to be displayed anywhere. If not already available then this needs to be added

**Comment by ajrbyers** [comment]
@mauromsl it looks like none of the Onetasker forms are saving notes, can you take a look?

**Comment by ajrbyers** [comment]
@twakeford now resolved.
