### ISSUE TITLE
Reviewer files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#209]
I (the editor) selected the files that I wanted the reviewers to see, however when I go to do the reviewer task I can see all of the files associated with the submission.

This ties in a little with making files only available after the review is accepted (separately logged issue), however only the files selected by the editor should be viewable by the reviewer

**Comment by ajrbyers** [comment]
- [ ] Stop displaying review files before the Reviewer has accepted
- [ ] Only display the files selected by the Editor
