### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#210]
When deleting files from the 'Submission Details' page the error message 'Server Error (500) is displayed

**Comment by twakeford** [comment]
On the same page, the 'Versions' button goes to an error message 'Not found' if there are no previous versions to display

**Comment by IoannisCleary** [comment]
@twakeford  When a file has no previous version it should only display the current version. 
![screenshot from 2016-01-05 14 28 34](https://cloud.githubusercontent.com/assets/5523178/12117442/baad3e2e-b3b8-11e5-8851-72f259b7d2a2.png)

else

![screenshot from 2016-01-05 14 29 52](https://cloud.githubusercontent.com/assets/5523178/12117469/d7feaa94-b3b8-11e5-82d3-fa61bcac878e.png)
