### ISSUE TITLE
Reviewer interests/specialism

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#212]
We need to add a 'Review interests' field for the registered reviewers. This should then be available on the 'Add reviewers' option in the Review workflow so that editors can filter the database for suitable people already in the system.

The current system will be hard to manage once there are many reviewers in the system. A search feature for name and review interests will make this more manageable.

**Comment by ajrbyers** [comment]
Reassign this to me.

**Comment by ajrbyers** [comment]
OKay, this needs to be added to the Registration and Add User forms. See how I've done this for keywords and disciplines on the Catalog page.

- [ ] Add Interests model with "Name" as a field
- [ ] Add tagit to all of the add user forms
- [ ] Handle the tagit on post the same way we handle keywords on the catalog

**Comment by IoannisCleary** [comment]
a32df55e692ef9270926af840015a91b40969e0d

**Comment by twakeford** [comment]
The list of reviewers visible to the editor when assigning a reviewer still does not list the interests within a user profile. I have the interests 'publishing' and 'open access' in my profile but this is not visible or searchable using the data available to the editor.
Interests listed in the profile should ideally be in the table of potential reviewers listed on screen, as well a searchable via the current search box
