### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#213]
When I go into an existing user's account their Roles are all unselected. This means that if I edit a separate part of their account details then I have to also remember to re-select the roles that they should have = All existing roles must be visible/remain when editing an existing user so that the editor doesn't have to re-add them each time.
![roles auto removed](https://cloud.githubusercontent.com/assets/15159847/11927578/6f0e8030-a7c5-11e5-85bb-c3b432d49347.png)

**Comment by IoannisCleary** [comment]
@twakeford The roles are selected when I access the page. Is the user edited via /manager/user/ ?

**Comment by ajrbyers** [comment]
I can confirm this...

**Comment by twakeford** [comment]
Weird: So, for the UP account, if I go into Andy or Caroline's account then the roles are not selected, but for the rest they are....
Andy (https://up.rua.pm/manager/user/2/edit/)
![screen shot 2016-01-05 at 17 26 31](https://cloud.githubusercontent.com/assets/15159847/12122204/7aa168c8-b3d1-11e5-851b-c86477eda7ba.png)

Caroline (https://up.rua.pm/manager/user/5/edit/)
![screen shot 2016-01-05 at 17 26 52](https://cloud.githubusercontent.com/assets/15159847/12122212/87636638-b3d1-11e5-9a00-bd75004ad672.png)

Me (https://up.rua.pm/manager/user/4/edit/)
![screen shot 2016-01-05 at 17 27 20](https://cloud.githubusercontent.com/assets/15159847/12122220/97a7d858-b3d1-11e5-8028-d826d8d23101.png)
