### ISSUE TITLE
High priority: Proposal reviewers unable to access details

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#214]
I thought that this had already been reported, but I can't find the issue logged, so placing here:

When a proposal has a reviewer assigned to it, the review task doesn't show in the reviewer dashboard. This means that there is currently no way for the proposal to be reviewed. As the proposal process is part of the big improvements we're offering, could this be looked into?

Apologies if this is a duplicate issue

**Comment by IoannisCleary** [comment]
The proposal review task appears when I assign a reviewer to a proposal.

![screenshot from 2016-01-05 13 01 00](https://cloud.githubusercontent.com/assets/5523178/12116323/fa079ae0-b3b0-11e5-8cb6-67775bf7ccb2.png)

**Comment by twakeford** [comment]
Strange - could you check it out for the SUP installation? There are currently 4 proposals showing at http://sup.rua.pm/proposals/ and I am assigned to each of them as a reviewer, but my reviewer dashboard doesn't show anything (http://sup.rua.pm/review/dashboard/).

![screen shot 2016-01-05 at 13 39 44](https://cloud.githubusercontent.com/assets/15159847/12116466/e74bb250-b3b1-11e5-94c8-91a4411d7487.png)
![screen shot 2016-01-05 at 13 39 58](https://cloud.githubusercontent.com/assets/15159847/12116468/e7647434-b3b1-11e5-8146-21ca1c35a456.png)

**Comment by IoannisCleary** [comment]
@twakeford It looks like the SUP installation is not up to date. Might need to talk to @ajrbyers

**Comment by ajrbyers** [comment]
Its up to date now.
