### ISSUE TITLE
Proposal form

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#216]
1) When an element has been added in stage 2 of the proposal creation process there is no method to then edit it. If edits are required then it needs to be deleted and re-added, which is not ideal.
Also - will it be possible to delete a form element that was in use?

2) When at stage 3 of creating a proposal form I get a Server Error (500) when trying to add the top available element to the proposal form (related to issue 3, below)

3) When a field is chosen to add to the proposal form, the element that has been selected is not the element that is then added to the list of 'Existing fields'. In the examples screen shots, the ORCiD element was selected, but the Email element is then displayed. The pattern seems to be that the element above the one that has been selected is displayed.

![selecting orcid](https://cloud.githubusercontent.com/assets/15159847/12063257/5b879368-afa3-11e5-8bfd-90736f52cc5f.png)
![not showing orcid](https://cloud.githubusercontent.com/assets/15159847/12063259/65d07ba0-afa3-11e5-9771-435916e1774f.png)

4) how can the default elements of 'title', 'subtitle' and 'author' be removed/edited? They appear to be the first parts of the preview form but do not display in the list of elements/field that have been selected.
![preview](https://cloud.githubusercontent.com/assets/15159847/12063300/46a8c858-afa4-11e5-9a14-65e4597fb8b4.png)

5) a form preview button on the stage 3 page would be very useful. At present, to view the form the user has to press 'finish', view the preview and then go back a stage if they want to make edits. The preview should be more accessible before the form is 'finished'.

**Comment by twakeford** [comment]
3) When a field is chosen to add to the proposal form, the element that has been selected is not the element that is then added to the list of 'Existing fields'. In the examples screen shots, the ORCiD element was selected, but the Email element is then displayed. The pattern seems to be that the element above the one that has been selected is displayed.

![selecting orcid](https://cloud.githubusercontent.com/assets/15159847/12063257/5b879368-afa3-11e5-8bfd-90736f52cc5f.png)
![not showing orcid](https://cloud.githubusercontent.com/assets/15159847/12063259/65d07ba0-afa3-11e5-9771-435916e1774f.png)

**Comment by twakeford** [comment]
4) how can the default elements of 'title', 'subtitle' and 'author' be removed/edited? They appear to be the first parts of the preview form but do not display in the list of elements/field that have been selected.
![preview](https://cloud.githubusercontent.com/assets/15159847/12063300/46a8c858-afa4-11e5-9a14-65e4597fb8b4.png)

**Comment by IoannisCleary** [comment]
@twakeford title, subtitle and author are default fields so they cannot be removed or edited

**Comment by twakeford** [comment]
Can they not be optional? Each press will want a different format for their proposal forms therefore this needs to be as flexible as possible. Things such as subtitle may not even be required by some presses as this stage, or just put within the 'title' field.

Not the biggest problem now if this really isn't possible, but full flexibility of the proposal forms should be the target for longer term.

**Comment by twakeford** [comment]
(sorry, pressed the wrong button - didn't mean to close)

**Comment by ajrbyers** [comment]
Hi,

These fields are part of the model, but not necessarily "required" fields. I think they should be displayed as these are also standard fields on a submission and are mapped if a proposal is accepted.

A

**Comment by twakeford** [comment]
Ok - that is a good reason for keeping them, if they then map up to the full submission. They need to be identical to the submission data then, e.g. 'Author' needs to change so that first and last name are separate fields.
Are there any other fields that would be useful to include that map to full submission then?
An annoying request, but can we start the form with the author names and then proposal titles?

**Comment by IoannisCleary** [comment]
I completed this issue, if you need something to be added to it please reopen it

**Comment by IoannisCleary** [comment]
@twakeford do you want me to add an edit feature for the fields too? (only available for form elements)

**Comment by twakeford** [comment]
@IoannisCleary probably not at this stage. If the elements are always going to be there then having an edit button will lead to people trying to make changes that they can't do. We can review after more partners have tested it.

**Comment by IoannisCleary** [comment]
@twakeford It might be good to have a 'edit order' button because there's no way that you can change the order after you have added the field

**Comment by twakeford** [comment]
ok - if the order can be edited then you're right that this would be useful.

**Comment by twakeford** [comment]
If data from the proposal form can map into the submission data upon acceptance, then should we discuss how best to do this? There will be some elements that can be optional, but would be very handy to avoid the author duplicating their efforts (affiliation, email, ORCID etc). Worth talking about next week?

**Comment by ajrbyers** [comment]
C'est possible.

**Comment by twakeford** [comment]
Has 1) of this card been completed? I'm creating a SUP proposal form now, which I believe was updated today, and the ability to edit or move elements within the form is not present.

**Comment by ajrbyers** [comment]
I'm at my inlaws house and haven't been able to do an update yet.

**Comment by twakeford** [comment]
ok, not a problem. I'll be prepping tomorrow morning, so leave it as it is.
They know it is a 1.0 and having some updates to show them in the future
isn't a bad things.

Enjoy the inlaws!
