### ISSUE TITLE
Proposal reviewers - add review option needed

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#218]
The review page for proposals needs to have a button added so that an editor can add a potential reviewer that is not already on the database

![proposal reviewers](https://cloud.githubusercontent.com/assets/15159847/12063919/efea2c0e-afae-11e5-8498-2516166a0f92.png)

**Comment by twakeford** [comment]
Is this linked to the first point in #191?

**Comment by ajrbyers** [comment]
Yes.

**Comment by ajrbyers** [comment]
The add new user button is now on this page, top right.
