### ISSUE TITLE
Submission checklist items

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#220]
We can add submission checklist elements, however once they are added it is not possible to remove or edit their content. We need both of these features.

e.g: https://up.rua.pm/manager/submission/checklist/
![screen shot 2016-01-05 at 17 14 52](https://cloud.githubusercontent.com/assets/15159847/12121943/19bf500c-b3d0-11e5-8b96-78daf6dfb0ad.png)

**Comment by IoannisCleary** [comment]
Screenshot:
![screenshot from 2016-01-06 10 24 40](https://cloud.githubusercontent.com/assets/5523178/12140448/fd014ff2-b45f-11e5-8e38-33f50eab1459.png)
