### ISSUE TITLE
Full screen not available

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#221]
The display window now doesn't allow the user to see the bottom of the screen when viewing the book pages. I believe that this is a new issue not previously present.
The 2 following examples show that various columns cannot view the bottom of the column in a normal laptop window size, and there is not option to move the window lower. There is no scroll option for the window as a whole, only the individual columns, which seems to cut off information from the viewable screen. The only way I could see the full screen info was by having the window on my big screen and enlarging the window (which is not an option for a lot of users).

e.g. http://sup.rua.pm/editor/submission/46/status/  The left column does not show the editorial decision buttons at the bottom and the middle column has the padding cut off
![screen shot 2016-01-06 at 11 40 31](https://cloud.githubusercontent.com/assets/15159847/12141815/cb423318-b46a-11e5-9aad-16822fbde12f.png)

E.g. http://sup.rua.pm/editor/submission/46/editing/view/copyeditor/2/ The left column has the bottom options cut off and the right column cannot show the full information.
![screen shot 2016-01-06 at 11 41 39](https://cloud.githubusercontent.com/assets/15159847/12141818/d43f2c28-b46a-11e5-9690-9180d5c87040.png)

**Comment by IoannisCleary** [comment]
Screenshot : 
![screenshot from 2016-01-06 11 53 50](https://cloud.githubusercontent.com/assets/5523178/12141980/524df6ac-b46c-11e5-9840-debe13cf1590.png)

**Comment by twakeford** [comment]
This should not be closed - I do have this problem on multiple pages. 
For example, even when I use my large screen, this submission details screen cuts off the bottom of the middle column (the competing interests data) and I do not have the scroll options to change this display
http://sup.rua.pm/editor/submission/46/
![screen shot 2016-01-06 at 11 57 58](https://cloud.githubusercontent.com/assets/15159847/12142045/db24e1c0-b46c-11e5-99dd-112175726f3b.png)

If you do not see the problem that is reported can they not be discussed rather than closed? Closing them makes it hard to work out what has been fixed and what not.

**Comment by ajrbyers** [comment]
Tim,

This issue is closed with a commit. Which means a fix has been pushed to the repo.

Andy
