### ISSUE TITLE
Email attachment problems

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#222]
There are 3 issues with the attachments sent via the RUA email:
1) the attachment is not available via the email log. This would be very useful to have accessible, as it will store things such as the versions of contracts, files asking for specific revisions etc. Please could this be added to dev work?

2) the attachment is not readable for the recipient of the email. The Word file that I sent to myself has no file extension and cannot be opened with Word. It says that it is a Textedit document, however this does not display the content. As there is no extension, Github won't let me attach it here.

3) the file name of the attachment is the RUA coded name, not the original file name. This needs to be changed so that the original file name is retained. The file that I sent to myself is now called '8f540498-6c62-4276-b535-0bb452bdba76'

**Comment by ajrbyers** [comment]
- [ ] Record attachments in the email log, display download link
- [ ] Use the original file name for the file (see the serve file view)

This will fix all three issues.
