### ISSUE TITLE
Competing Interests Page

### ISSUE THREAD

**Issue by IoannisCleary** [ubiquitypress/rua#224]
- [x] Add new page competing-interests
- [x] Link to CI page should be in help text

Taken from:
#191  #186

**Comment by IoannisCleary** [comment]
@ajrbyers What should this page display ?  (The competing interests of a submission : title + container with text )

**Comment by twakeford** [comment]
@IoannisCleary I think that this refers to a page where we can list what constitutes a competing interest, so that the author knows what it is that they need to declare during the submission. The text on this page should be editable by the press manager, as presses may have different requirements.

**Comment by ajrbyers** [comment]
It's just a page setting. Will show you when in the office later.

Andy Byers
Technical Architect, Ubiquity Press

**Comment by ajrbyers** [comment]
So all you need to do is add a page setting to the settings.json and link to its page. You'll need to add a url that will look like:

http://example.org/page/setting_name

and the function will look like:

```

def about_page(request, page_name):

	page_content = request.settings.get(page_name, None)

	if not page_content:
		raise Http404

	template = 'website/page.html'
	context = {
		'page_content': page_content,
	}

	return render(request, template, context)
```
