### ISSUE TITLE
Request Revisions Missing Template

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#225]
When requesting revisions on a proposal I get the following error:

```
Internal Server Error: /proposals/3/revisions/
Traceback (most recent call last):
 File "/home/tech/.virtualenvs/rua/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/var/www/vhosts/rua_deploy/sup/src/core/decorators.py", line 54, in wrap
   return function(request, *args, **kwargs)
 File "/var/www/vhosts/rua_deploy/sup/src/core/views.py", line 1381, in request_proposal_revisions
   'email_text': logic.setting_template_loader(setting=email_text,path="core/proposals/",pattern="email_template_",dictionary={'sender':request.user,'receiver':proposal.owner}),
 File "/var/www/vhosts/rua_deploy/sup/src/core/logic.py", line 40, in setting_template_loader
   html_file= open(file_location,"w")
IOError: [Errno 2] No such file or directory: u'templates/core/proposals/email_template_proposal_request_revisions.html'
```

This should be using a setting, not a template.

**Comment by IoannisCleary** [comment]
@ajrbyers This works for me, it loads a temporary template file in order to use it to render the django template tags of a setting. This works for me.
![screen shot 2016-01-11 at 09 56 12](https://cloud.githubusercontent.com/assets/5523178/12230396/3e4d979a-b848-11e5-8788-154ed20b2a4b.png)

**Comment by IoannisCleary** [comment]
@ajrbyers 
This might provide a temporary fix     [

#Create folders that do not exist		

    if not os.path.exists(file_location):
        os.makedirs(file_location)

]

**Comment by ajrbyers** [comment]
It's unnecessary. You don't need to load a template in order to use the Django template system.
