### ISSUE TITLE
Proposal information display & editing

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#229]
1) We need proposal forms (and all forms and text blocks) to keep their formatting rather than show the html tags. The information in a proposal can get long and the paragraph breaks and other typical formatting are required. Currently the text that was provided in paragraphs is displayed as a block of text with <p> tags showing.

![screen shot 2016-01-11 at 11 27 05](https://cloud.githubusercontent.com/assets/15159847/12232414/481c1dba-b856-11e5-9044-e6c336eea05b.png)

2) the proposal form needs to be editable from the editor side as well as from the author side so that editors can correct information prior to sending it to review. I thought that this was already listed as an issues, but cannot find it.

3) notifications should be sent to editor/author when proposal information is updated

**Comment by ajrbyers** [comment]
Also, the Go Back button takes you to the Editor Dashboard not the Proposal Dashboard.

**Comment by ajrbyers** [comment]
1. 58f0ae5d1109ee1cf047983ae1539bd7afff0c52

2. Editors CAN edit these, but it would be better if they used HTML. @IoannisCleary to fix.

3. @IoannisCleary is adding functionality for Editor to be notified when Author edits the proposal.

**Comment by twakeford** [comment]
re 2. how/where can the editors edit the proposal info?

**Comment by IoannisCleary** [comment]
@twakeford An editor can edit the proposal information from the proposal page of the proposals dashboard

**Comment by twakeford** [comment]
Thanks - yes, I completely missed this. It is an excellent feature!
