### ISSUE TITLE
proposal review: form availability

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#230]
Currently the proposal reviewer can only see the proposal form in the left column of the page. This is going to be unworkable, as real proposals can go to many pages of text, making this column extremely long. We therefore need to:
1) find a better on-screen solution to review the information. The current window also doesn't fit the width of the text within the form, so some of the data is not visible.
2) make the form downloadable, so that the reviewer can take it offline, should they need to
3) remove html tags so that on-screen display retains formatting (thus making it easier to read)

**Comment by IoannisCleary** [comment]
@ajrbyers @twakeford   Is this a better display of the proposal's details ?
![screen shot 2016-01-11 at 14 13 52](https://cloud.githubusercontent.com/assets/5523178/12235518/4b719fd8-b86c-11e5-98d5-2068bdfbf3ea.png)

**Comment by twakeford** [comment]
@IoannisCleary looks a lot better. Will have to see it 'live' to confirm, but it looks good to me. Are points 2 and 3 also included in this redesign?
