### ISSUE TITLE
Email settings

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#233]
Please have email settings updated, as per https://docs.google.com/a/ubiquitypress.com/spreadsheets/d/1ytWUHQv8OVxXSsMjkMgWLqSqB5N523DzbHqgYuk01oA/edit?usp=sharing

**Comment by ajrbyers** [comment]
- [ ] Add Tim's settings to the email settings and format them properly (use the user.profile.salutation_name for the person's name)
- [ ] Export to the settings fixture

**Comment by IoannisCleary** [comment]
@ajrbyers @twakeford Settings have been updated. There are still some template tags in the setting values that do not match context passed in (some revision and review related settings).  I tried to check if most of them work correctly but someone might need to test them.
