### ISSUE TITLE
Padding/page display

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#234]
I'm still having padding issues with the content at the bottom of pages.

e.g. http://sup.rua.pm/editor/submission/51/

Unless I zoom out then I can't access the information at bottom of the middle or right columns
![screen shot 2016-01-12 at 10 26 16](https://cloud.githubusercontent.com/assets/15159847/12261136/274d2c2a-b917-11e5-9bf8-15b8c8808fe7.png)

**Comment by ajrbyers** [comment]
I can. Are you zoomed in by default? The site is designed to work at "100%" zoom,

**Comment by twakeford** [comment]
Nope, I've cmd+0 'd it and it is still a problem

**Comment by IoannisCleary** [comment]
@twakeford  Could you tell me your screen's resolution so I can check when the page's (bottom) space/padding is not enough ?

**Comment by twakeford** [comment]
they both are showing as 'default for display'. Where else can I find the
info?

[image: Inline images 1]

**Comment by IoannisCleary** [comment]
@twakeford Your screenshot should be the same resolution as your screen (unless you had to resize it) :)

**Comment by IoannisCleary** [comment]
@twakeford  My screen's resolution is smaller than yours and it seems to be working fine.
![screenshot from 2016-01-18 16 03 23](https://cloud.githubusercontent.com/assets/5523178/12396055/3efa55ec-bdfd-11e5-966f-8ef91598eb05.png)

**Comment by ajrbyers** [comment]
hey @IoannisCleary it looks like @twakeford is using Firefox and you are using Chrome. I've confirmed this is an issue in Firefox so can you investigate? Thanks,

**Comment by IoannisCleary** [comment]
@ajrbyers Okay I'll look into it now

**Comment by IoannisCleary** [comment]
@ajrbyers @twakeford  This update should fix most (if not all pages). If there are pages that still are not displaying correctly, please reopen this issue
