### ISSUE TITLE
Editorial notes

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#235]
One thing that I don't think it currently available on RUA is a notes section for editors to leave internal comments, thoughts, updates, plans etc. Could we find a place to add such a feature? I don't have strong feeling on where, although the Submission Details page would make a little sense.

- [x] On the Editor menu add a new "Notes" button 
- [x] Add a new page that will allow an Editor to view notes
- [x] On this page also display previously added notes
- [x] We should record: the note, the user and a timestamp (all three should be displayed neatly on the page)
- [x] Interface should be in keeping with the Editor section

**Comment by ajrbyers** [comment]
Ok I'll spec this out.

**Comment by ajrbyers** [comment]
- [ ] On the Editor menu add a new "Notes" button 
- [ ] Add a new page that will allow an Editor to view notes
- [ ] On this page also display previously added notes
- [ ] We should record: the note, the user and a timestamp (all three should be displayed neatly on the page)
- [ ] Interface should be in keeping with the Editor section

**Comment by IoannisCleary** [comment]
@ajrbyers Will this page be part of a submission ?  (or are they just general notes)
I assume by record that it's a new model.

**Comment by ajrbyers** [comment]
Yes, FK to the Book! So only noted for a given book should display!

**Comment by IoannisCleary** [comment]
![screenshot from 2016-01-12 17 40 47](https://cloud.githubusercontent.com/assets/5523178/12271588/cc44db6a-b953-11e5-8642-a6628511e24b.png)
