### ISSUE TITLE
Add Proposals to Overview

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#242]
- [x] add new column to the overview for proposals
- [x] display unaccepted/declined proposals
- [x] display review and revisions dates

**Comment by IoannisCleary** [comment]
in proces proposals added to overview + style update: 176182c545a36e10c4664cb952e3fd1e76487ed3

**Comment by IoannisCleary** [comment]
@ajrbyers revision dates are not recorded , only when the review process started and review assignments
