### ISSUE TITLE
On “Set Due Date” page for a review, update “Submit Query” to some better text

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#248]

**Comment by IoannisCleary** [comment]
@ajrbyers  I'm not sure what needs to be changed, I can't see where it says "Submit Query"

Screenshot :  
![screenshot from 2016-01-14 10 14 54](https://cloud.githubusercontent.com/assets/5523178/12321803/0f75da42-baa8-11e5-8b3c-e0a40f67e3ea.png)
