### ISSUE TITLE
Production Editor

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#252]
- [x] Add new FK to the Book for a User called ProductionEditor
- [x] Add new role Production Editor (production_editor)
- [x] On Move to Production allow the Editor to select from a list of users with the Production Editor role
- [x] Make sure Production Editor is added to the roles.json

- [x] Add a second email field that will allow the Editor to send an email to the selected Production Editor

**Comment by IoannisCleary** [comment]
- [ ] Update decorators.py
