### ISSUE TITLE
Email 'from' name

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#253]
When an email is sent from RUA it often has the sender listed as 'main' (see screenshot).
Can we have this to be something more understandable?
![screen shot 2016-01-18 at 13 23 52](https://cloud.githubusercontent.com/assets/15159847/12392436/fd00a666-bde6-11e5-93a1-01e121349fbf.png)

**Comment by ajrbyers** [comment]
These are settings that can be changed. Closing.
