### ISSUE TITLE
Reviewer: Instructions for task

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#254]
Where is the 'Instructions for task' setting editable? This screen shot shows the text as it is when the reviewer is invited, but I can't see a setting to edit this. If is is not available, please could this be made editable?
![screen shot 2016-01-18 at 13 44 59](https://cloud.githubusercontent.com/assets/15159847/12392826/cff2818c-bde9-11e5-9228-18f931f73952.png)

**Comment by IoannisCleary** [comment]
@twakeford  The selected review form comes with introduction text and completion text where you can add more information about the task. (Example introduction text: 'intro')
![Uploading Screenshot from 2016-01-18 16:19:56.png…]()

**Comment by ajrbyers** [comment]
@IoannisCleary he's wondering what the setting name is?

**Comment by IoannisCleary** [comment]
@ajrbyers there is no setting should I add one for each type of assignment ? (review,proposal,typeset,index,copyedit)

**Comment by ajrbyers** [comment]
Ah. There should be an instructions_for_task setting for each of them and they appear under the "INSTRUCTIONS FOR TASK" section on the left. Remove the _intro_ text on the right.

**Comment by IoannisCleary** [comment]
@ajrbyers okay but if the introduction text will never be used then why have it as part of the form ?

**Comment by ajrbyers** [comment]
@IoannisCleary ah, I thought that image was the "completed review" page. So yeah just add a setting for each of them and put them in the settings.json :)

**Comment by IoannisCleary** [comment]
@ajrbyers Okay :+1:
