### ISSUE TITLE
Description for Manager options

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#255]
Settings within the Manager options currently don't have descriptions of what function the settings have and where they appear/what pages they effect. Some are more obvious than others, but having instruction from the start would be very useful as external press editors will get access to these settings. Could setting descriptions therefore be added to the existing settings/Cron list etc and have new settings in the future include these as default? - e.g. 'direct submissions' = does ticking it enable or disable full submission?

**Comment by IoannisCleary** [comment]
@ajrbyers  We could add a description variable to the Setting model

**Comment by ajrbyers** [comment]
Yes please go ahead and do this

**Comment by IoannisCleary** [comment]
Added description for boolean settings + added description to template: c7f9e1a208afa030be0d7a75dcb55ebc8efa3b1a
