### ISSUE TITLE
Submission.Views, queries that are not required

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#256]
```
		'suggested_reviewers': core_models.Setting.objects.get(name='suggested_reviewers').value,
		'suggested_reviewers_guide': core_models.Setting.objects.get(name='suggested_reviewers_guide').value,
```

The above queries are not required as these settings are available in the Context Processor, on the template you can do:

{{ press.general.suggested_reviewers }}

**Comment by IoannisCleary** [comment]
@ajrbyers does this apply to all settings (email text for example) that are needed in pages or just those two?

**Comment by ajrbyers** [comment]
Just these two for now. But we should update these during a later code review.

**Comment by IoannisCleary** [comment]
f88db9e0a759b5554641984b695e589f72f55f85
