### ISSUE TITLE
New user password

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#257]
When an editor creates a new user account the new users password pops up in a green box in the bottom right corner but then disappears after a few seconds. The password needs to be more permanent until the editor moves away from the page, as they are likely to need to copy it and provide it to the new user.

**Comment by IoannisCleary** [comment]
@twakeford I have a sort of fix for this where I extend the timeout from 5 seconds to a minute and add a close button so you can dismiss it before the timeout. Do you want me to add this change?

**Comment by twakeford** [comment]
That certainly sounds better. Is is possible to keep the password available
to the editor? I'm just thinking that if they need to, for example,
register a reviewer, copyeditor etc, then they could complete the
registration, then process the invitation (find the right page, edit the
email etc), and only then need to add the password. Not an urgent one.

I assume that there is a key for the email templates to provide passwords,
so I'll have to make sure that they are present in all the relevant emails.

**Comment by ajrbyers** [comment]
Alternatively, we could email the password to the user.

Andy Byers
Technical Architect, Ubiquity Press

**Comment by twakeford** [comment]
Could do, the main issue with that is that we want to reduce the amount we
bug reviewers. This method would mean that the user receives an unsolicited
email saying that they've just been registered with RUA, and at some point
later (hopefully soon, but not necessarily) an email from the editor would
appear inviting them to review. It may be confusing.

Could it be an option for the editor to choose during the registration,
like in JMS?
