### ISSUE TITLE
Form setup workflow

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#261]
There are a few confusing parts of setting up review forms. In general, can the proposal and review form processes be made identical? Currently they are some differences, such as where the preview form is, what can and cannot be edited etc, which make editing a little more confusing. the Proposal form workflow currently seems a little more understandable. If not, then:

Review forms:
1) When creating review forms the 'Element Class' is required, however no description of what is needed is available. please could this be updated so that the format matches the proposal form format, so that this is a drop down with 'full', 'half', 'third'.
2) Review form is only available by clicking the 'finish' button. the preview is needed earlier so that we can see how the form is building
3) elements and fields are not editable after they have been entered

**Comment by twakeford** [comment]
In general, can the proposal and review form processes be made identical? Currently they are some differences, such as where the preview form is, which make editing a little more confusing.

**Comment by IoannisCleary** [comment]
c329cd8d72d6ac0da917c011ea6c21a3da33880c  Replaced element class with width dropdown selection + added preview of review form

**Comment by IoannisCleary** [comment]
1a49a97cff54cd0f8f18287a5d156d0238aff1b6 Added review form element edit feature
