### ISSUE TITLE
Form building error

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#264]
There is still a bug in the creation of forms, although it seems inconsistent and I can't find a pattern to it:
e.g. 1:
1) I add the field 'Are conclusions presented.....' and have it set to order '9'
2) click the 'add' button
![screen shot 2016-01-29 at 11 01 12](https://cloud.githubusercontent.com/assets/15159847/12673937/e6f4f2fc-c677-11e5-9799-0acf6f616f58.png)

But, when in the form, it has selected a completely different element
![screen shot 2016-01-29 at 11 01 38](https://cloud.githubusercontent.com/assets/15159847/12673946/f4ad4d90-c677-11e5-8d83-580b67c0fe9a.png)
![screen shot 2016-01-29 at 11 01 23](https://cloud.githubusercontent.com/assets/15159847/12673949/f7a5732e-c677-11e5-873f-697f2db90c6a.png)

I have just created this form, and it only happens for this element. I cannot get 'Are conclusions presented.....' into the form at all (http://template.rua.pm/manager/review-forms/form/1/add/field/)

e.g. 2:
It also seems to have now duplicated another of the elements that was previously only showing in order 3, which may or may not be related to the same bug
![screen shot 2016-01-29 at 11 05 38](https://cloud.githubusercontent.com/assets/15159847/12674008/4f348e36-c678-11e5-828b-81ed440662cf.png)

e.g. 3:
I edited a field that was at order 9 to be order 1, but it has removed the field that was at 9 and duplicated a different field in the field list. The preview form has removed the field that was at 9 but move moved it anywhere else
![screen shot 2016-01-29 at 11 14 39](https://cloud.githubusercontent.com/assets/15159847/12674199/917baa1c-c679-11e5-8e0a-24b4953f9eba.png)

**Comment by IoannisCleary** [comment]
@twakeford  this problem sounds like it's related to the first part of #263. Elements were listed by id and not by position in the list. A fix has been uploaded for 263. Can you please try again and see if it works ?

**Comment by twakeford** [comment]
@IoannisCleary that seems to now work. Having the list ordered by ID wouldn't have added a different element or duplicated an existing element though. I'm not convinced that all the bugs are out of this, but won't have time for further testing until next week

**Comment by IoannisCleary** [comment]
@twakeford  Okay. Let me know next week if the bug still exists :)
