### ISSUE TITLE
Suggested reviewer settings

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#265]
There are currently two settings that appear to be a duplicate:

http://template.rua.pm/manager/settings/group/general/setting/suggested_reviewers_guide/
http://template.rua.pm/manager/settings/group/general/setting/review_suggestions/

Could the difference in use please be explained for each setting description, or the duplicate removed?

**Comment by ajrbyers** [comment]
@IoannisCleary can you run a search across files (find in folder) to see where these are used?

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers  review_suggestions only appears in some test data and tests.py . Suggested_Reviewers_guide is the one that is used in the first stage of submitting a new book

**Comment by ajrbyers** [comment]
Ok, lets swap them around.

**Comment by IoannisCleary** [comment]
@ajrbyers remove review_suggestions?

**Comment by ajrbyers** [comment]
Yep. and update the tests.

**Comment by IoannisCleary** [comment]
@ajrbyers okay
