### ISSUE TITLE
Proposal form subtitle field

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#266]
The proposal form currently has 'Subtitle' labelled as a mandatory field. Please change this to optional, as some books will not have a subtitle

**Comment by IoannisCleary** [comment]
@twakeford fixed it, it was not actually required just marked as required by mistake.

**Comment by twakeford** [comment]
@IoannisCleary ok - they aren't manually labelled though, are they? Do they not link to the option to set the field as 'required' or not?

**Comment by IoannisCleary** [comment]
@twakeford no they are not manually labelled, i didn't have an if statement check for the default fields (title, subtitle, author). I only had one for the generated fields (any field that is created by the user)
