### ISSUE TITLE
Incomplete Emal Settings

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#269]
The following settings on Template need to be completed. If you need to them, do so on your local machine but ensure the final version is also copied onto template (copied not loaddata as Template is now the master settings repo)

- http://template.rua.pm/manager/settings/group/email/setting/proposal_accept/
- http://template.rua.pm/manager/settings/group/email/setting/proposal_decline/
- http://template.rua.pm/manager/settings/group/email/setting/proposal_request_revisions/ (Due date?)
- http://template.rua.pm/manager/settings/group/email/setting/revisions_reminder_email/
- http://template.rua.pm/manager/settings/group/email/setting/typesetter_typeset_request/

**Comment by IoannisCleary** [comment]
123bed42838576d81ba1e1c9f0c0714ab5c688d1 - added revision due date for proposals - updated author tasks,dashboard +request revision page (added due date field) + added overdue display update + fixed proposal_accept/decline/request_revisions settings
