### ISSUE TITLE
User registration permissions

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#270]
I just registered Tom Mowlam onto the Template RUA. I gave him all of the permissions, which show up correctly when I review his profile

![screen shot 2016-02-03 at 16 31 08](https://cloud.githubusercontent.com/assets/15159847/12788977/c5ef3868-ca93-11e5-90e4-685acf487b32.png)

and when I review the users under specific roles (e.g. this is those registered as press editors)

![screen shot 2016-02-03 at 16 30 49](https://cloud.githubusercontent.com/assets/15159847/12788998/df22defc-ca93-11e5-99f0-029c005016ef.png)

BUT - when I log in as Tom, he only has reviewer and author dashboard showing and can't access the Manager or Admin options in the profile drop down menu
![screen shot 2016-02-03 at 16 31 21](https://cloud.githubusercontent.com/assets/15159847/12789018/fa4512e0-ca93-11e5-9a6e-d3e1ff5d230f.png)

The only way that I have found to fix this is for me to log in under my account and then go to Users in Admin to give him staff or superuser status.

A fix is therefore needed so that roles are applied as per the registration.

**Comment by ajrbyers** [comment]
Neither of these roles allows a user to access the settings or admin and this is expected.

**Comment by ajrbyers** [comment]
- [ ] Add is_staff checkbox for enhanced permissions.

**Comment by twakeford** [comment]
Press Editor should have editor permissions /dashboard & access to Manager option.
Access to Admin is not required external to UP
Series Editor should presumably have editor permissions but not access to either Manager or Admin

**Comment by ajrbyers** [comment]
@staff_required replaced with @is_press_editor on Manager pages.

Update the entire nav structure (by which I mean, add some logic to the nav structure)

Commit: 08690cd970a42110ad467371d2f99e269f2b5dee
