### ISSUE TITLE
Review form error

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#271]
The current review form in Template, 'Proposal Review Form' is showing that there are 19 existing fields in the form, many of which are duplicates (http://template.rua.pm/manager/review-forms/form/2/add/field/)
![screen shot 2016-02-03 at 16 39 44](https://cloud.githubusercontent.com/assets/15159847/12789218/cae131cc-ca94-11e5-847b-f8d137e9bc80.png)

The preview form below this only shows 9 fields within the form. These 9 fields are correct, as I don't want the duplicates included, but it is very hard to edit the form when the list of fields doesn't match the preview.
Please can this be looked into?

**Comment by ajrbyers** [comment]
Proposal form list:

<img width="1393" alt="screen shot 2016-02-13 at 23 27 45" src="https://cloud.githubusercontent.com/assets/8321378/13030629/6c3485da-d2a9-11e5-8077-4541e498632a.png">


Simple interface:

<img width="1381" alt="screen shot 2016-02-13 at 23 26 55" src="https://cloud.githubusercontent.com/assets/8321378/13030624/4d8d8474-d2a9-11e5-8546-c8f603b0a8cc.png">

Preview:

<img width="1453" alt="screen shot 2016-02-13 at 23 27 24" src="https://cloud.githubusercontent.com/assets/8321378/13030626/5d3be4e2-d2a9-11e5-974c-220de4c64d41.png">
