### ISSUE TITLE
Author revisions - how to add new files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#273]
One thing that has fallen off the radar is the ability for the author to add new files during the author revisions stage. They can upload new versions of existing files, but we also need to give them the option of uploading new files (e.g. if I ask them to remove all images from their manuscript file and provide them as separate files).
(This is possibly the largest oversight I have found in our feature list.)

**Comment by ajrbyers** [comment]
- [ ] Update Revisions page to allow user to upload additional files
