### ISSUE TITLE
Add new user - Go back button

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#274]
When an editor is inviting reviewers they can press the 'Add New User' button to add a reviewer not currently on the database. This correctly takes them to the registration form.
But, if the 'Go Back' button is clicked, it does not take the editor back to the page that they left, but instead a general list of all users in the manager page. 
= the Go back button should link to the previous page

e.g.
http://template.rua.pm/manager/user/add/
click the go back button takes to
http://template.rua.pm/manager/user/
when it should go to e.g.
http://template.rua.pm/proposals/5/review/add/

**Comment by ajrbyers** [comment]
Added with commit c7d3155d647479d37eeef6cc9481e476125d8623

**Comment by twakeford** [comment]
@andy @IoannisCleary Just tested this on the live UP site and it is the same as originally described above - clicking 'Go Back' doesn't take me to the previous review page but the list of users.
