### ISSUE TITLE
Standardise date in email keys

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#276]
Can we standardised the way dates are provided in emails? During testing I received the below text in the email when asking the author to make revisions. This is from the {{revision.due}} key

![screen shot 2016-02-03 at 17 31 13](https://cloud.githubusercontent.com/assets/15159847/12790792/f1656fb4-ca9b-11e5-8af3-793976cb92a8.png)

When invited to review, the reviewer received the below, from the {{review.due}} key
![screen shot 2016-02-03 at 17 35 35](https://cloud.githubusercontent.com/assets/15159847/12790918/8e158fa6-ca9c-11e5-83c4-3add96972657.png)

Can this please be standardised, preferably to the top display to avoid confusion over whether the date is display yyyy-mm-dd or yyyy-dd-mm?

**Comment by ajrbyers** [comment]
Default date format set to Y-m-d which outputs to 2016-01-01.

**Comment by twakeford** [comment]
Is it not possible to have the more obvious format of 10 Feb 2016? As reviewers/authors will be global and have different standard format, this would be far more unambiguous (how is an author supposed to know if 2016-03-04 is 4th March or 3rd April?)

**Comment by ajrbyers** [comment]
YYYY-mm-dd is the ISO date format so we're gonna go with that. 👍🏼

**Comment by twakeford** [comment]
ISO can bite my arse
