### ISSUE TITLE
enhanced editor permissions

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#277]
Now that we have the option to assign editors to a submission then we should also have the ability to filter out submissions that are not assigned to the user.
The thinking is that a press editor may do the initial assessment of the submission and then assign it to another editor. The other editor will not need to see any other submissions within the system.
Ideas to do this would be to add filters to 'show only my assignments' (or something similar) or to have a second level of editor (similar to JMS).

**Comment by ajrbyers** [comment]
Would you prefer:

- Allow Book Editor to see all submissions but only access their own
or
- Only allow Book Editors to see their own submissions?

**Comment by twakeford** [comment]
I think that the second option. It will create a cleaner interface for the user and if they're not interacting with the other books then they won't need to see them
