### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#278]
Email templates:
- author_copyedit_request - add deadline date key needed (I don't have a list of the keys to know this)
- author_typeset_request - add deadline date key (I don't have a list of the keys to know this)
- book_editor_ac - when this is sent and how after what task/action? There needs to be a description - added to detail what this relates to before I can edit the email template
- decision_ac - is this for all Editorial Decisions or only rejections? Not a problem either way, but I need to know before finalising the template
- request_revisions - need to add URL link to the system (I don't have a list of the keys to know this)
- from_address - who should this link to, the main press contact's email address?
- task_decline - what does this refer to?
- unaccepted_reminder - is '/original sent date/‘ a working key? All the others are enclosed by {{}}

**Comment by ajrbyers** [comment]
author_copyedit_request - add deadline date key needed (I don't have a list of the keys to know this)

- Feature does not exist

author_typeset_request - add deadline date key (I don't have a list of the keys to know this)

- Feature does not exist

book_editor_ac - when this is sent and how after what task/action? There needs to be a description - added to detail what this relates to before I can edit the email template

- Description added to template

decision_ac - is this for all Editorial Decisions or only rejections? Not a problem either way, but I need to know before finalising the template

- Its used for all decisions.

request_revisions - need to add URL link to the system (I don't have a list of the keys to know this)

- Key added

from_address - who should this link to, the main press contact's email address?

- Yes.

task_decline - what does this refer to?

- Its for a future feature where, when a task is declined the user can email the Editor and tell them why.

unaccepted_reminder - is '/original sent date/‘ a working key? All the others are enclosed by {{}}

- No it should be {{ review.assigned }}

**Comment by ajrbyers** [comment]
For the first two, if this is something thats required, let me know.

**Comment by twakeford** [comment]
Both would definitely be useful but not essential for the roll out
