### ISSUE TITLE
Peer review declaration

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#284]
We should add a button within the catalogue pages to link to the portal to display whether the book has been peer-reviewed or not. Currently I think that this can be done in JURA by Paige, but some presses won't pay for publishing services so will need to do it themselves.

This may be particularly relevant for presses loading back content.

**Comment by ajrbyers** [comment]
Editors/Production staff can now mark peer-review override in the Catalog.

<img width="513" alt="screen shot 2016-02-11 at 13 44 29" src="https://cloud.githubusercontent.com/assets/8321378/12977930/bcbd3c30-d0c5-11e5-963a-beb401d44626.png">
