### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#286]
Having the proposals info on the overview page may look bad when there are multiple books at full submission. If there are more than a couple of books in one stage (e.g. in Review) then this list will push the proposal details down the screen and potentially with a lot of white space between the cards. 

I would suggest that we add a button to the page that allows the editor to toggle between books in proposal stage and books in full submission stages. We could then also break the proposal process into stages as well to show that it is being worked on. It may also be nice to have accepted or declined proposals in 1 data feed as an archive, with their accepted/rejected status. This would save some space on the page but with the same info for editors.
(in general this page may need a re-spec on layout to maximise potential)

**Comment by ajrbyers** [comment]
Tim, in the meantime, I've made two overview pages. Feel free to put a spec together for further changes.

A
