### ISSUE TITLE
new submission email key

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#289]
I received the editor new submission email, but the link to the submission doesn't work. It shows up in the email as:

The book details can be accessed at localhost:8000/editor/submission/3/.

The setting for the 'editor_submission_ack' is set to:

The book details can be accessed at {{base_url}}/editor/submission/{{submission.pk}}/.

Please could this be updated/fixed so that the link works in the received email?

**Comment by ajrbyers** [comment]
This isn't actually a bug. The base_url for the template press is set here:

http://template.rua.pm/manager/settings/group/general/setting/base_url/

And reads localhost:8000 so the URL is correct according to the data. I've updated it so links should now work. http://template.rua.pm/editor/submission/3/
