### ISSUE TITLE
Email display

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#290]
When an editor invites a reviewer the email box that the editor sees retains the html tags and is in a single paragraph, making it very hard to read and edit.

![screen shot 2016-02-12 at 15 58 14](https://cloud.githubusercontent.com/assets/15159847/13012058/93677f3a-d1a1-11e5-81ae-6b54cd3ea569.png)

Ideally this box will show the text that is going to be received with the tags removed. If this is not possible then the spacing/formatting of the email should display.

**Comment by ajrbyers** [comment]
Ensure all email <textareas> blocks are HTML.

**Comment by twakeford** [comment]
in addition to the above, I noticed that some of the tags are retained in the received/logged email. They seem to open/close ok, so can't see an obvious reason why they would show.

![screen shot 2016-02-12 at 16 31 15](https://cloud.githubusercontent.com/assets/15159847/13013172/39a04428-d1a6-11e5-9bc2-6b5d662b87dc.png)
