### ISSUE TITLE
Link accepted proposals to proposal details

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#295]
At present there is no link from an accepted proposal (status 'in progress') or full submission back to the proposal log. This will definitely be required therefore we need to link the two. Possibly a link in the Submission details or Catalogue pages? The proposal should be read-only once accepted but should list all of the correspondence, review history and proposal history/edits

**Comment by ajrbyers** [comment]
- [ ] Add an FK to a Book to link it to a Proposal
- [ ] When a proposal is accepted set this FK
- [ ] Display the proposal info in the timeline alongside the book info

**Comment by ajrbyers** [comment]
In addition, we should also check if there is a Proposal linked to a submission and bypass this lovely bit of code:

```
if not direct_submissions:
		return redirect(reverse('proposal_start'))
```

so it should be:

```
if not book.proposal and not direct_submissions:
		return redirect(reverse('proposal_start'))
```

**Comment by IoannisCleary** [comment]
@ajrbyers 

Since there's a possibility of not book id it should be
`if book_id:
		book = get_object_or_404(core_models.Book, pk=book_id, owner=request.user)
		if not book.proposal:
			return redirect(reverse('proposal_start'))`

**Comment by ajrbyers** [comment]
will need to see the full code block ;)

**Comment by IoannisCleary** [comment]
@ajrbyers okay, it's  start_submission in submission.views. if a book is not created you can't access the proposal variable

**Comment by ajrbyers** [comment]
Go ahead and commit your change, I'll review it after.

**Comment by ajrbyers** [comment]
The change you made wont stop the redirect from happening if you're in a proposal generated book.

**Comment by ajrbyers** [comment]
```
if not direct_submissions:
		return redirect(reverse('proposal_start'))
``` 

Should be moved to the ELSE block shouldn't it?

**Comment by IoannisCleary** [comment]
@ajrbyers 
`
	if book_id:
		book = get_object_or_404(core_models.Book, pk=book_id, owner=request.user)
		if not book.proposal:
			return redirect(reverse('proposal_start'))
		book_form = forms.SubmitBookStageOne(instance=book, ci_required=ci_required.value)
		checklist_form = forms.SubmissionChecklist(checklist_items=checklist_items, book=book)
	else:		
		if not direct_submissions:
			return redirect(reverse('proposal_start'))
		book = None
		book_form = forms.SubmitBookStageOne()
		checklist_form = forms.SubmissionChecklist(checklist_items=checklist_items)
` ?
