### ISSUE TITLE
Tick box settings

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#297]
When I deselect the setting suggested_reviewers and submit the change the change does not save. Each time that I access the setting the box is ticked

e.g. http://sup.rua.pm/manager/settings/group/general/setting/suggested_reviewers/

**Comment by twakeford** [comment]
This is also a problem for the setting 'preview_review_files'

The workaround is to access the admin page and remove 'None' from the value box, but this needs a more solid fix as the people editing settings won't necessarily have access to Admin or have the knowledge of where to look

**Comment by ajrbyers** [comment]
Fixed with: f863fb6a18ead9f2a55dc30eb92350108389ab92

Rolling out to UP live server now.
