### ISSUE TITLE
Review form: sections

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#299]
Allow section heading of the review form to be added, so that headings can be added without having an element required to accompany them. (very minor)

(example attached showing how a review form may have questions under different section headings)
[SUP_Book_Peer_Review_Form.docx](https://github.com/ubiquitypress/rua/files/152937/SUP_Book_Peer_Review_Form.docx)

**Comment by ajrbyers** [comment]
Marked as wontfix for now. May come back to it later.
