### ISSUE TITLE
Profile display

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#300]
When viewing my profile, the user name is not aligned correctly and underlays the email address

![screen shot 2016-03-03 at 10 42 34](https://cloud.githubusercontent.com/assets/15159847/13491861/bb80fd58-e12c-11e5-8a22-205ff0657900.png)

**Comment by IoannisCleary** [comment]
![screen shot 2016-03-03 at 11 12 07](https://cloud.githubusercontent.com/assets/5523178/13492220/c26e6cfc-e12e-11e5-831b-29a9863e35b4.png)
