### ISSUE TITLE
Editor submission on behalf of....

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#305]
Can we please add a feature so that a Press/Book Editor can submit a book proposal on behalf of an author?

The logic is that a number of proposals will be sent to us as general enquiries via email rather than on RUA. Ideally we can ask them to complete the form, but in some instances it may be better to create and account and copy and paste the existing details, rather than asking the author to complete the form. The editor could create an account for them and add the proposal details and 'submit' on their behalf. The author could then be sent a submission confirmation email with their proposal details.

This would also allow easier cascading of books from one press to another, as a rejected proposal from one press may be recommended to another (which has just happened SUP to UP) without the need for the author to complete the same proposal form.

**Comment by ajrbyers** [comment]
This can be achived by adding the proper owner as an author then using the "Change Owner" function on the catalog.

**Comment by twakeford** [comment]
Needs re-opening as owners can only change at submission, not proposal stage

**Comment by ajrbyers** [comment]
@IoannisCleary how difficult do you think it would be to allow a user to assign someone else as the owner of a proposal? Would probably need:

- [ ] Link to create a new user
- [ ] Function to change owner

**Comment by IoannisCleary** [comment]
@ajrbyers  @twakeford  I can add a 'submit a proposal' button in the proposal dashboard. the page will look the same but it will have a tick to mark it as unassigned or assign to myself. It might be better to have a table of unassigned proposals so the editor can create a proposal and assign it to someone after. In this way you can even create a new user without losing any data.

**Comment by twakeford** [comment]
@IoannisCleary that sounds good. Having the option available to the editor via the Proposals Dashboard makes sense. Having unassigned proposals could work well, and then the editor creates a user and assigns the proposal so that the new user is the owner.
Having the proposal history log each of these actions would also be nice to record so that the real original of the proposal is clear (e.g. can't setup a proposal in someone else's name without it being recorded)
