### ISSUE TITLE
Proposal email history

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#306]
There isn't currently and email or event log for proposals. The data is recorded but not displayed = we need to surface this info so that all events and correspondence is available.

**Comment by twakeford** [comment]
@IoannisCleary has this been rolled out? I can't see any history events/emails option when viewing proposals

**Comment by IoannisCleary** [comment]
@twakeford the email log will appear in the submission log page at the email log tab. Until a proposal has been accepted the email log cannot be viewed

**Comment by twakeford** [comment]
@IoannisCleary well that isn't really what was requested - the point was that an email history is needed for a proposal editor during the proposal stage.

It also means that the proposal history will not be available unless the proposal is accepted = rejected or in process proposals cannot be audited.

History during a proposal is a required feature.

**Comment by twakeford** [comment]
Can this be re-opened as the original request seems to be misunderstood = the proposal events and emails need to be available in both the proposal stage and the post-acceptance workflow of the full submission

**Comment by twakeford** [comment]
See http://template.rua.pm/log/submission/16/ for e.g. of proposal info not tracking into the full submission

**Comment by IoannisCleary** [comment]
@twakeford all proposals (Accepted/rejectd) can be viewed from the history page on the proposals dashboard. Not sure about the third part, do you want a rendered form (like the start proposal page) ?

**Comment by ajrbyers** [comment]
3 - Link to view these from a linked submission, I presume?

**Comment by IoannisCleary** [comment]
@ajrbyers Okay, should i add the link on the submission details page or log page?

**Comment by twakeford** [comment]
If not too late, adding a link to th Submission details page would make most sense.

**Comment by ajrbyers** [comment]
That's where it went
