### ISSUE TITLE
Proposal user details

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#307]
Can we have the submitting user profile surfaced to the proposal editor? The editor will need to know the affiliation, email address, ORCID and possibly social media accounts (essentially more info the better) during the editor’s assessment of the proposal. We can add these things to the proposal form, but as we're asking the author to register this seems like duplicating their efforts.

Either pulling this information automatically into the form, or having a 'view profile' option associated with the submission would be ok.

**Comment by IoannisCleary** [comment]
Readonly profile : bb2ff2d7496ab4b5f1d810a58d077fc148cea229
