### ISSUE TITLE
Removal of assigned reviewer

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#308]
Add the ability of an editor to withdraw an assigned reviewer from proposal or submission review (reasons most likely being that they do not respond to the email invitations)

**Comment by ajrbyers** [comment]
Peer review should be marked as withdrawn.

Reviewer should not be able to access the review

Editor should be able to re enable the review

**Comment by IoannisCleary** [comment]
@ajrbyers if you delete the review assignment (feature already exists for book reviews) it will be deleted from the system and the reviewer can't access it. Re enable review can be done by assigning a new review assignment to the user. I'll add a similar feature for proposal reviews.

**Comment by ajrbyers** [comment]
HI @IoannisCleary, @twakeford wants a record that the reviewer was invited so wants an additional option to Withdraw the review.
