### ISSUE TITLE
Email display to add reviewer

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#309]
When adding reviewers, the email display when adding the first reviewer is different from when adding subsequent reviewers. The second view is not good and needs to be made consistent with the original email display.
e.g.
1. Editor clicks 'Start Review Process'
![screen shot 2016-03-04 at 10 50 12](https://cloud.githubusercontent.com/assets/15159847/13525173/534d44e6-e1f7-11e5-8127-7c59f93cbe86.png)

2. Editor sees an invitation template that does not show the email tags
![screen shot 2016-03-04 at 10 50 21](https://cloud.githubusercontent.com/assets/15159847/13525184/61b2f6b6-e1f7-11e5-93c5-883153155572.png)

3. If the editor then may click 'Add Reviewer' to invite another person (perhaps the original rejected the invitation)
![screen shot 2016-03-04 at 10 50 33](https://cloud.githubusercontent.com/assets/15159847/13525202/81021d1c-e1f7-11e5-9e98-2547f005274a.png)

4. The email display is now back to a display that has the template showing all tags and in a single paragraph
![screen shot 2016-03-04 at 10 50 39](https://cloud.githubusercontent.com/assets/15159847/13525226/9a2c772e-e1f7-11e5-8436-e71d320b7544.png)

= please can all emails display similarly to the first example?

**Comment by ajrbyers** [comment]
- [ ] Ensure JQTE is used for all emails in the Proposal section

**Comment by twakeford** [comment]
I haven't tested, but as the review pages are the same for proposal and full submission review, can it be checked that they both have this?

**Comment by ajrbyers** [comment]
@IoannisCleary can you also:
- [ ] Ensure this is okay for full book reviews
