### ISSUE TITLE
Blind proposal review

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#310]
Currently when we invite a reviewer to a proposal they are able to see the author name
![screen shot 2016-03-04 at 11 20 43](https://cloud.githubusercontent.com/assets/15159847/13525764/3adcd080-e1fb-11e5-89d6-927595b7d86f.png)

It is likely that some presses will want the review to be blind. This may require careful form building (and will be helped by #307). We therefore need to have a mechanism for the editor to choose if review should be blinded so that information that IDs the author is removed from the reviewer page

**Comment by ajrbyers** [comment]
- [ ] Allow Editor to set review to BLIND when adding a proposal review
- [ ] If review is blind, don't let the Reviewer see the Proposer's details.
