### ISSUE TITLE
Add 'in progress' books to Overview page

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#311]
Currently the Overview page  lists submissions from full submission onwards (e.g. https://up.rua.pm/overview/). This means that books that have had their proposals accepted but not yet submitted are not covered by either the Overview or Proposals Overview page.

= we should add 'In progress' (possibly re-label this term this to 'not yet submitted') to the overview page so that books expected for submission are visible

**Comment by IoannisCleary** [comment]
Preview of in progress overview
![screenshot from 2016-03-04 15 37 44](https://cloud.githubusercontent.com/assets/5523178/13531565/212ed3f8-e21f-11e5-9508-d1c93dec990b.png)

**Comment by twakeford** [comment]
Are they listing the stages of the submission process - i.e. the different pages?

**Comment by IoannisCleary** [comment]
@twakeford The stages are submission stages (i added the 6th step too, not in the preview). It shows which steps were completed and where in the submission process the in progress submission is. When the submission process is done (stage 6 has been completed), the submission is not shown in the in progress section

**Comment by IoannisCleary** [comment]
updated screenshot
![screenshot from 2016-03-04 15 48 07](https://cloud.githubusercontent.com/assets/5523178/13531860/9161be78-e220-11e5-9b9d-3725f2fd64bf.png)

**Comment by IoannisCleary** [comment]
Navbar update screenshot: I added a divider between overview pages and published books 
![screenshot from 2016-03-04 15 51 23](https://cloud.githubusercontent.com/assets/5523178/13531963/0560e858-e221-11e5-9717-4f3e2cf86275.png)

**Comment by twakeford** [comment]
I was thinking that this would be a list within the current Overview tracker. Would this not work? If it is on a page on its own this won't it just be a single list? On the main overview page makes sense, as it is used for planning projects, so seeing how many have been signed up for submission would be useful alongside the already submitted projects.
Whilst it is nice to see the stages of the submission process, I imagine most will all complete the submission in the single task. If this makes any difference.

**Comment by IoannisCleary** [comment]
@twakeford   Adding another list would mean that it will appear below the existing ones and since the outer scroll bar has been removed and since in the future the current lists will be way longer, the user will not be able to scroll down to view it. So a different page is better

**Comment by twakeford** [comment]
ok - happy to keep as is then and review as we get real projects coming in
