### ISSUE TITLE
Author Dashboard - rejected projects

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#312]
The author dashboard lists all projects, whether they are in process or already rejected. When 'view proposal' is clicked then there is no indication that the editorial decision has been to reject it. In the below, all of the proposals have been rejected, but how is the author to know this?
![screen shot 2016-03-04 at 11 40 36](https://cloud.githubusercontent.com/assets/15159847/13526155/fa0b00b0-e1fd-11e5-9cd9-47a73c0584e9.png)

We therefore should:
1. Clearly indicate that the project has had an editorial decision and what that decision is in the summary box and in the proposal/submission details page
2. We should remove rejected proposals and submissions from their main dashboard page so that it is as clean as possible. It is good to keep the info available to the author, but perhaps via a 'Previous submissions' button on the dashboard that leads to a separate page.

**Comment by ajrbyers** [comment]
- [ ] Display Editor Decision in Purple Bar
- [ ] Display Editor Decision in View Proposal page
