### ISSUE TITLE
Proposal review: additional rounds

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#317]
At present, a proposal reviewer can only be assigned once = would be good to have:

1) option of multiple review rounds = a) reviewer completes review, b) editor asks for author revisions, c) author submits revisions, d) editor asks reviewer to review the revised content according to a new round of review

2) Reviewer submits an incomplete or unacceptable review = editor can re-open the review stage and send it back to them asking them to comment further on this. Ideally this would keep the existing review data available to the reviewer so that they can keep all of their feedback in one place.

**Comment by ajrbyers** [comment]
@twakeford whats your preference?

**Comment by twakeford** [comment]
Can I have both? They are two different scenarios.

If I have to choose, then option 1

**Comment by ajrbyers** [comment]
Ok. Both it is. @IoannisCleary, can you add some check items for this one, once done tag me and I'll review.

**Comment by IoannisCleary** [comment]
-[ ] Notify reviewer of updated proposal and ask to review the latest version (reopens the review with previous comments (in the case that the same problem exists), add new due date option)
- [ ] Reopen just reopens the review  if incomplete (add new due date option or add message option)
@ajrbyers

**Comment by IoannisCleary** [comment]
https://github.com/ubiquitypress/rua/commit/e4a5ed028b71eb522d4b3a01c99f656b853aadc3
