### ISSUE TITLE
Editor email notification

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#320]
When a reviewer has completed their task and submitted the review, an auto email should be sent to the assigned editor/editor that requested the review to notify them that the feedback is available for them to assess

**Comment by ajrbyers** [comment]
Should be dealt with by daily digest emails. Info to follow.

**Comment by ajrbyers** [comment]
- [ ] Add new cron setting for "every X day notification reminders should be sent"
- [ ] Add attribute to notification "emailed" boolean.
- [ ] Add new cron job to find editors with notifications and, if they have any where emailed = False, generate an email that lists the notifications
- [ ] Mark those notifications as emailed=True so they don't get sent again

**Comment by ajrbyers** [comment]
@IoannisCleary if you have questions about the CRON app, let me know so we can chat about it before you start this one.
