### ISSUE TITLE
Author revisions: Delete files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#324]
Give author the option to delete files from the list of submission files (e.g. a figure is being removed). The current interface only allows existing files to be replaced, not removed

**Comment by ajrbyers** [comment]
- [ ] Allow author to delete files during a Book revision

**Comment by twakeford** [comment]
@IoannisCleary this only seems to be partially completed. I see that it is now possible for the author to remove a manuscript file (good), but they still can't remove an additional file (bad) - it needs to be an option that all files are removable (e.g. if a figure is deemed inappropriate or not available due to copyright, then it needs to be removed)
![image](https://cloud.githubusercontent.com/assets/15159847/14350944/4bca94ac-fcc4-11e5-91cf-ba65eef29b3a.png)

**Comment by twakeford** [comment]
Also - when I clicked the delete button shown in the above screen shot, it took me back to the main Author Dashboard. If a file is being deleted then please keep the user on the same page (and possibly have a pop up to confirm they want to delete a file)
