### ISSUE TITLE
Data from proposal to submission

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#326]
Have the compulsory information on the proposal form that transfers to the full submission edited as below:

1. change the current heading 'title' to 'Book Title'
2. change 'Author' to 'Submitting author/editor' (ideally pull this info from their registered account)
3. add the selection of whether it is an edited volume or monograph to this form so that it is clear at proposal stage and set by the author/editor, rather than selected by the Press Editor when accepting the proposal

**Comment by ajrbyers** [comment]
- [ ] Update the verbose_name (i.e. don't change the field name for the above.)

**Comment by IoannisCleary** [comment]
@twakeford  Is this correct?  
![screenshot from 2016-03-08 16 27 40](https://cloud.githubusercontent.com/assets/5523178/13608019/c959a9ee-e54a-11e5-88cd-96ef3037d389.png)

**Comment by IoannisCleary** [comment]
@twakeford  It's not possible to select volume/monograph on that page as it is not stored in the proposal db model but retrieved from the list and added to the submission when the proposal is accepted.

**Comment by twakeford** [comment]
@IoannisCleary yep, that looks better, cheers.

For the monograph/edited vol, is this something that could be implemented in the longer term? It's not a big thing, but it just seems like something that the editor would want to know at the start of the proposal process from the author rather than the editor set this at the end of the process. No urgency on this though.

**Comment by IoannisCleary** [comment]
@twakeford  Okay so we can move the monograph/volume feature to a new card so we'll look at it in the future
