### ISSUE TITLE
Mandatory field notification

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#330]
When a mandatory field is not completed in a proposal form the form needs to show the user where they still need to add data.

In Safari, this is shown with red text at the form element in question = Good

In Firefox, this is shown by a small box that appears on the screen but does not link to the section of the form in question = Bad
![screen shot 2016-03-10 at 16 52 47](https://cloud.githubusercontent.com/assets/15159847/13677215/e1057d42-e6e0-11e5-87b3-2fc427c85971.png)

Could it be updated so that there is more consistent and direct display of where the user needs to add more data

**Comment by IoannisCleary** [comment]
this is a jqte error (text editor plugin). firefox is not a problem. fields are highlighted correctly

**Comment by ajrbyers** [comment]
Can you clarify @IoannisCleary ? What is the error with jqte thats causing this?

**Comment by IoannisCleary** [comment]
@ajrbyers  not sure but if you don't add the jqte  the message appears under the field, if you do it appears under the address bar.

**Comment by ajrbyers** [comment]
So it doesn't scroll to the correct location if JQTE is enabled?

**Comment by IoannisCleary** [comment]
@ajrbyers  yes

**Comment by ajrbyers** [comment]
We could try swapping them for Summernote fields?

**Comment by IoannisCleary** [comment]
@ajrbyers I'll test summernote now

**Comment by IoannisCleary** [comment]
@ajrbyers same problem with summernote. it says that the object is not focusable

**Comment by IoannisCleary** [comment]
Error message: An invalid form control with name='(name)' is not focusable.

**Comment by IoannisCleary** [comment]
@ajrbyers  @twakeford  a solution could be to add a message popup of which field should be completed.

**Comment by twakeford** [comment]
Having it relate to the element on the form would be better - the forms can be long so a pop up can still be hard for the user to know exactly which section they should pay attention to.

**Comment by ajrbyers** [comment]
JQUERY should be able to scroll to the label, @IoannisCleary

**Comment by IoannisCleary** [comment]
@ajrbyers the object is not focusable in jqte/summernote... Error message: An invalid form control with name='(name)' is not focusable.

**Comment by ajrbyers** [comment]
Yeah, but Im not talking about focus, Im talking about scrolling to the label....

**Comment by IoannisCleary** [comment]
@ajrbyers  okay i'll try

**Comment by IoannisCleary** [comment]
after many tries to make it display or highlight fields, this is the only solution that kind of works. it creates an alert message and when you click on the field name it takes you to it (scrolls down). cannot validate in other way since the error doesn't allow you to make a request
![screenshot from xcxc-03-15 16-05-08](https://cloud.githubusercontent.com/assets/5523178/13784697/29db0fce-eac8-11e5-873b-c18db96985f1.png)

**Comment by twakeford** [comment]
that looks good to me. Does the screen automatically go to the top of the
page, so that the message will be visible automatically, rather than the
author having to scroll up the page?

Tim Wakeford
Editorial Manager
Ubiquity Press

E: tim.wakeford@ubiquitypress.com <szekiu.yeung@ubiquitypress.com>
S: tim.wakeford
T: +44 (0) 207 3230343
W: http://www.ubiquitypress.com

**Comment by IoannisCleary** [comment]
@twakeford  I updated the method to scroll up to the error message
