### ISSUE TITLE
Registration linked to T&C

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#333]
We should probably have a checkbox for users to confirm that they agree to our T&C during the registration process. This would need to display if the press had T&C added to JURA, and have a link to this page when available (similar to what is being added to journals, I think)

- [x] Add new page setting "terms-conditions"
- [x] Add new profile attribute "terms_and_conditions" - Boolean
- [x] In the label for the terms and conditions display a link to the terms-conditions page

**Comment by ajrbyers** [comment]
Rua has no contact with Jura at all at the moment. Though we could pull these via the API.

**Comment by twakeford** [comment]
Assuming that RUA will be linked to JURA soon (as in, we need it to stop using OMP), then add to this work package? the T&C isn't urgent though

**Comment by ajrbyers** [comment]
Ah. You're thinking of something else entirely. I mean Rua is standalone and has no way to contact Jura (book publishing is done by Jura PULLING from Rua)

I'll consider how to do this.

**Comment by ajrbyers** [comment]
- [ ] Add new page setting "terms-conditions"
- [ ] Add new profile attribute "terms_and_conditions" - Boolean
- [ ] In the label for the terms and conditions display a link to the terms-conditions page
