### ISSUE TITLE
Series Management

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#334]
At present it doesn't look like Press Editors (or any role) can manage series via the RUA settings.

= We need to add settings to the Manager options that can create and edit series and then manage associated books to them once they are setup

- [x] Add interface for editors and series editors to add new series
- [x] Utilising the same view, allow them to edit existing series (see how this has been done with User management)
- [x] Allow editor to delete a series, before hand warning them which books will be orphaned from the series
- [x] Allow editor to add books to a series using a datatable with checkboxes

**Comment by ajrbyers** [comment]
- [ ] Add interface for editors and series editors to add new series
- [ ] Utilising the same view, allow them to edit existing series (see how this has been done with User management)
- [ ] Allow editor to delete a series, before hand warning them which books will be orphaned from the series
- [ ] Allow editor to add books to a series using a datatable with checkboxes
