### ISSUE TITLE
'Log in as' feature

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#335]
Could we add a feature so that Press Editors and Book Editors have the option to 'log in as' another user? This is a feature of JMS that is particularly useful for managing projects.

This has been requested by Kriterium, as they say that the current OMP system requires this feature a lot. Whilst we should try to encourage authors, reviewers etc to use the system there will always be some that won't/can't. The experience from JMS is that this would be very useful.

If possible, then it would be great for any actions carried out whilst 'logged in as' to appear within the logs so that it is clear that the editor was acting on the author's behalf. JMS shows that it is the owner of the account that carried out the action, even when it was someone logged in as them. It would be good not to replicate this ambiguity.

**Comment by IoannisCleary** [comment]
Screenshots: 
1-
![screenshot from 2016-03-31 16-03-59](https://cloud.githubusercontent.com/assets/5523178/14180329/743b6f48-f75a-11e5-93ed-ec6133c07381.jpg)

2-
![screenshot from 2016-03-31 16-05-14cc](https://cloud.githubusercontent.com/assets/5523178/14180332/778dd622-f75a-11e5-91ef-f341c361bfbb.jpg)
