### ISSUE TITLE
Download all

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#337]
Add an option to 'download all' files.

Editors, reviewers & authors will each at some point need to open each file associated with the submission. At present they need to click individually on each file to download it. As books may have many files, please can we add a 'download all' option when files are listed.

**Comment by ajrbyers** [comment]
Zip the files up and then download? Delete the ZIP afterwards.

**Comment by twakeford** [comment]
Zip em up sounds good to me
