### ISSUE TITLE
Add Number of Notes

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#338]
<img width="402" alt="screen shot 2016-03-16 at 17 48 12" src="https://cloud.githubusercontent.com/assets/8321378/13822893/521487fe-eb9f-11e5-80e1-4f3cc728bd76.png">

- [x] Display number of notes on the book sidebar.

**Comment by IoannisCleary** [comment]
![screenshot from 2016-03-17 10-30-41](https://cloud.githubusercontent.com/assets/5523178/13843427/74c93eb6-ec2b-11e5-98bd-84c039b3ad90.jpg)
