### ISSUE TITLE
Versioning of proposals

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#339]
I have no idea if this is possible, but could we try to add a way to show how a proposal has been edited? Currently there are email alerts when a proposal have been edited but no way of showing what the edit was.
Frank pointed out that a proposal form could be many pages long and revisions could be relatively small. He won't know what has changed without reading the full proposal again and even then doesn't have anything to compare it against as the original version is over written.
Any ideas on how to help this? Something like tracked changes, I guess....

(title is a little misleading, as versioning isn't really the correct term, but couldn't think what else to call it)

**Comment by IoannisCleary** [comment]
@twakeford One way to implement this is to store in a new model all the proposal details (new model for each save) and link it to the main model. Another way is to add a model with a text field where before you save the changes, each field is compared and a string/text is created saying 'This field changed from "" to  "" '

**Comment by twakeford** [comment]
@IoannisCleary which option did you go for?
