### ISSUE TITLE
MAP & WUP settings page is down

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#344]
The MAP & WUP settings page currently does not show any setting options, only the headings - see screen shot

![screen shot 2016-03-29 at 15 04 21](https://cloud.githubusercontent.com/assets/15159847/14110713/9561b156-f5bf-11e5-8560-7499a706756d.png)

![screen shot 2016-03-29 at 15 01 32](https://cloud.githubusercontent.com/assets/15159847/14110638/3ad399c0-f5bf-11e5-852f-e562d5fe3619.png)

Please could this be looked into ASAP, as I will be demoing this to MAP on Thursday

**Comment by IoannisCleary** [comment]
@twakeford  both website dbs have no settings that's why the pages are empty

**Comment by IoannisCleary** [comment]
@twakeford  Andy added the settings so it should be fine now
