### ISSUE TITLE
Series editor does not receive email notification when external review is done

### ISSUE THREAD

**Issue by asakellariadi** [ubiquitypress/rua#346]
I wasn't able to test exactly this as I do not have admin access to the template and thus I could not create a series and assign a series editor but as a simple editor I did not receive any notification email after the completion of external peer review although I did receive a notification in my tasks log as editor in RUA.

**Comment by twakeford** [comment]
@IoannisCleary when a reviewer completed their assignment, who should an email go to? The assigned editor to that project?

**Comment by twakeford** [comment]
@asakellariadi based on @ajrbyers description earlier, the Series Editor role is to overview everything that is being processed for a specific series, but not necessarily to be the person processing the book. When part of a series, A Book Editor should be assigned (which could be the series editor), and it is they that will complete the tasks and receive the notifications (@ajrbyers to confirm)

**Comment by ajrbyers** [comment]
Confirmed.

**Comment by asakellariadi** [comment]
@twakeford when I tested the book editor did not receive an email either. So apparently currently nobody receives notifications. At least either the series or the editor should receive an email notification.

**Comment by asakellariadi** [comment]
From what seems to be the way Kriterium expect to use the system, they would like the series editor to receive an email notification as well. I think that it depends a lot on the workflow of each press.

**Comment by asakellariadi** [comment]
@ajrbyers at least one email notification should be added before this closes :)

**Comment by ajrbyers** [comment]
Oh. You're talking about something totally different. Email notifications are not sent instantly and are rounded up and sent in batches. This is not yet enabled.

**Comment by twakeford** [comment]
Yep - the assigned editor should definitely be notified when a review is complete. If not already in place then @IoannisCleary can help to add that.
I don't think that the series editor would want to receive all notifications though, it could be a lot!

**Comment by asakellariadi** [comment]
So there will be email notifications coming as soon as the feature is enabled and these will be sent out say every 24 hours...OK, I can tell them that.

**Comment by ajrbyers** [comment]
Probably more like hourly. @IoannisCleary has already built the tool right?

**Comment by asakellariadi** [comment]
Cool! Thank you very much for the clarification! :)
