### ISSUE TITLE
Proposal access: 500 - Internal Server Error

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#348]
For the SUP account, I cannot view the proposal currently in http://sup.rua.pm/proposals/ as I receive a 500 error when I click View.

I have all roles, so I should have access.

SUP have also reported that some of them can see it whilst others cannot

**Comment by IoannisCleary** [comment]
@twakeford for some reason the subtitle field was required in the database model, i committed a fix.
cdd467eae877276bc0d5f8cc3cd7d9ebb69cd6df
