### ISSUE TITLE
Add cancel option to Editorial Decision

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#349]
Can we please add a cancel button once editorial decision buttons have been made?

E.g. Accidentally clicking the Request Revisions button when they meant Accept.....

**Comment by IoannisCleary** [comment]
@twakeford About the cancel button: should an email be sent to the editorial board that it has been cancelled? (Should an email be sent when review rounds are cancelled?)

**Comment by twakeford** [comment]
@IoannisCleary sorry, re-reading this, the original spec wasn't clear....

I think that I am correct that each editorial decision (accept, reject, request revisions) leads to an email template that notifies the author and then after this is sent moves the book to the next stage of the process. 
I would like a button so that if the decision button is pressed then instead of sending the email the editor can cancel the decision so that it is reversed and taken back to the previous screen = no email is sent to the author and the submission does not move to the next stage.
If the decision is made and the email sent, then that is a different thing, as the editor could not really have done that by accident.
