### ISSUE TITLE
Proposal not displaying

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#350]
The SUP installation of RUA is showing that a proposal has been submitted on the Editor Dashboard notification
![screen shot 2016-04-01 at 13 08 05](https://cloud.githubusercontent.com/assets/15159847/14206409/ccf73a44-f80a-11e5-8784-139def06c256.png)

But the Proposal Dashboard does not show this proposal, only an older proposal
![screen shot 2016-04-01 at 12 22 20](https://cloud.githubusercontent.com/assets/15159847/14206421/e21c90d6-f80a-11e5-87fc-fc1fbcfd2c8f.png)

= Can this bug please be looked into?

**Comment by IoannisCleary** [comment]
@twakeford bug has been fixed, maybe SUP has not been updated yet. All proposals can be viewed by press editors, other editors can view proposals that do not have a requestor/editor user or the requestor field user is the same with the logged in user.

**Comment by twakeford** [comment]
@IoannisCleary ok - how do we get the live installations updated? Is there a date for the next release?

**Comment by ajrbyers** [comment]
Releases are on Mondays.
