### ISSUE TITLE
Option to cancel a round of review to be added

### ISSUE THREAD

**Issue by asakellariadi** [ubiquitypress/rua#352]
New feature: A book editor should be able to cancel a new round of review - not only a specific invitation to review - either because it was initiated by mistake or because he/she changed their mind. 

- [x] Add option for Editor to cancel a review round, reinstating the previous round as the current

**Comment by ajrbyers** [comment]
@asakellariadi on the understanding that deleting a review round will also delete any information inserted into it.

**Comment by asakellariadi** [comment]
Yes, Andy.

**Comment by ajrbyers** [comment]
Great.

**Comment by ajrbyers** [comment]
@IoannisCleary can you work on this please?

**Comment by twakeford** [comment]
if deleting a round, even with review info in it, please could we have a confirmation pop-up to warn that this will happen? - i.e. a 2 step process to stop an editor clicking the delete button accidentally and removing info without confirming that they are happy to do so

**Comment by IoannisCleary** [comment]
preview (option only available for latest review round):
![screenshot from 2016-04-05 15-38-46](https://cloud.githubusercontent.com/assets/5523178/14285752/a0420c62-fb44-11e5-9cb0-3dcf1c351140.png)

popup preview:
![iojo](https://cloud.githubusercontent.com/assets/5523178/14285930/36b14186-fb45-11e5-9245-c30434736b2d.png)

**Comment by twakeford** [comment]
@IoannisCleary could we edit the text of the popup box a little so that it says 'All review assignments in this round of review will be deleted.'?

I just want to make it clear that it only effects this round, not all review assignments.

**Comment by IoannisCleary** [comment]
@twakeford  Sure, updating the message now.

**Comment by twakeford** [comment]
Ace - thanks!
