### ISSUE TITLE
Disable Proposal route

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#353]
Please can we add a setting that disables the option to submit a proposal, in the same way that we can disable direct submissions - i.e remove the option from the author dashboard?

This is unlikely to be used much, but some presses, such as MAP, only accept invited content and therefore will not be accepting proposals.

**Comment by ajrbyers** [comment]
- [ ] Add new setting
- [ ] If setting is enabled, users can not submit proposals. Should be hidden from the Submit drop down and redirect with a message if URL is typed
