### ISSUE TITLE
Date field in proposal form

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#356]
The template Proposal form currently includes the element 'estimated submission date' which is element type 'Date'.

I assume that this means that the user should see a calendar view when clicked on (or similar) so that a date is recorded.

This currently does not happen, as the proposal forms shows a basic text box where any characters can be entered = if the above assumption is correct then the Date element type has a bug.

**Comment by ajrbyers** [comment]
@IoannisCleary can you check this out?

**Comment by twakeford** [comment]
This needs to be re-opened as it still doesn't seem to work on template RUA = still just a text field

**Comment by IoannisCleary** [comment]
@twakeford can you post a link to the proposal that is causing the problem?

**Comment by twakeford** [comment]
@IoannisCleary all proposals on the template form: http://template.rua.pm/submission/proposal/

**Comment by IoannisCleary** [comment]
@twakeford it works on my local copy maybe SUP has not been updated yet
![screenshot from 2016-04-15 15-38-21c](https://cloud.githubusercontent.com/assets/5523178/14564851/437a9092-0320-11e6-94e6-ab7f78b37d14.png)

**Comment by twakeford** [comment]
I'm not on SUP, I'm on template, and Andy updated it before I started testing, so can't help there.... @ajrbyers ?

**Comment by ajrbyers** [comment]
![screen shot 2016-04-15 at 15 56 30](https://cloud.githubusercontent.com/assets/8321378/14565348/a87316c0-0322-11e6-8662-0a05a48afd76.png)

**Comment by IoannisCleary** [comment]
@ajrbyers @twakeford  the problem seems to be the name. i'll try and fix it
