### ISSUE TITLE
Assign editor to proposals

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#360]
Some presses will have multiple people working on proposals, so we will need to add a feature that allows proposals to be assigned to a specific Book Editor, who will be the primary point of contact. This is the same that has already been completed for full submissions.

When assigned, a Book Editor should be able to filter the proposals so that they only see those that are assigned to them.

**Comment by ajrbyers** [comment]
- [ ] Allow user to assign an editor to a proposal
- [ ] Allow user to filter list to only their proposals (though they should still be able to remove the filter and view all of them)
