### ISSUE TITLE
Download completed reviews button

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#365]
Feature request:
When a review has been completed, could you add a button so that the editor can download the completed content? (in a similar way that the reviewer can download the empty form).

The idea being that they can then assess the review offline (they can be very long)

**Comment by ajrbyers** [comment]
@IoannisCleary this one will need to be thoroughly tested with proper inputs... it may error on non ASCII content.

**Comment by IoannisCleary** [comment]
@ajrbyers Okay, the function is the same with the proposal form download in the proposals dashboard, but for review forms.
