### ISSUE TITLE
Re-opened review tasks

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#367]
There are a couple of errors when re-opening a review task:
1- When a review task has been re-opened the Editor can no longer access the original completed review task as it is removed from their page = they should still have access to the original (e.g. they may be only asking the reviewer to add a small comment in 1 section of the form and all the rest is still fine)

2- when a reviewer accesses a re-opened review proposal task, they do not get asked if they will accept the request to add more detail/the editors request. As such, the completed proposal form is not available to them = they should be able to see the completed proposal details

**Comment by IoannisCleary** [comment]
@twakeford since the reviewer accepted the first task, it is not necessary for them to accept the reopened task. I will add a second complete page that will not redirect and it will just render the completed review only if data exists

**Comment by twakeford** [comment]
@IoannisCleary point 2 concerns proposals only (I think) = when the review went back into the re-opened task they can see the incomplete proposal form, but they need to see the completed form. Is that what you meant?

**Comment by IoannisCleary** [comment]
@twakeford when the author is revising the proposal, they can see what information they entered as it is loaded.

**Comment by IoannisCleary** [comment]
@twakeford do you want the user to have a readonly page with the previously submitted data while they are revising their assignment's data?

**Comment by twakeford** [comment]
@IoannisCleary I think that we're talking about different things. This request is so that the reviewer of proposal can see the completed proposal form if the editor has re-opened the review stage and asked them to added further information. Currently, the reviewer cannot see the completed proposal form.

![image](https://cloud.githubusercontent.com/assets/15159847/14421993/606bbfa2-ffcc-11e5-9807-79042be08d16.png)

**Comment by IoannisCleary** [comment]
@twakeford the decision page didn't seem to load the proposal form data. I added a fix for that and tested it, the data seems to be loaded in the other pages.

**Comment by IoannisCleary** [comment]
@twakeford I'll close the issue for now and we can reopen it when the change goes live and it didn't fix the problem
