### ISSUE TITLE
500 error when editor submits a proposal using the new 'unassigned' submit option

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#369]
The Editor can complete the proposal form, but when they hit Submit I receive a 500 error = needs removing so the process can be tested

![image](https://cloud.githubusercontent.com/assets/15159847/14349102/932b4528-fcb8-11e5-9177-1690a914e3be.png)

**Comment by IoannisCleary** [comment]
@twakeford  I submitted a proposal  and assigned it to someone locally and i didn't get a 500 error

**Comment by twakeford** [comment]
@IoannisCleary weird - I just tested it again and it had the error again. 

We may be doing different things - I am submitting the proposal via the 'Unassigned' option on the proposal dashboard

**Comment by IoannisCleary** [comment]
@twakeford I tested it with the unassigned option. Maybe it has something to do with the form used on SUP. @ajrbyers is there a way to get the debug message for this ?

**Comment by twakeford** [comment]
I always upload a file as part of the proposal submission, as this seems to be a regular problem. Did you also attach a file to the proposal?

**Comment by IoannisCleary** [comment]
@twakeford no, I'll try adding a file field and see what happens

**Comment by IoannisCleary** [comment]
@twakeford yeah it was the file field. it was missing an import
