### ISSUE TITLE
Setting: Review type option

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#370]
Currently the author can chose a review type on page 1 of the submission.

![image](https://cloud.githubusercontent.com/assets/15159847/14349171/10f3aff4-fcb9-11e5-8a60-ab8514cbd2e1.png)

Some presses won't want to have options available to the author = we need to add a setting so that this can be turned on and off (also explain what difference each option makes, as 'open' review can mean different things)

**Comment by IoannisCleary** [comment]
I'll add two settings: one to enable/disable the selection and a setting for the default review type
