### ISSUE TITLE
Incorrect submission status

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#374]
I just requested revisions for a submission, which is logged in the event and email log (http://template.rua.pm/log/submission/13/)
![image](https://cloud.githubusercontent.com/assets/15159847/14349875/e8d2b60a-fcbd-11e5-8d35-0c62a858eb8d.png)

![image](https://cloud.githubusercontent.com/assets/15159847/14349885/f41717fe-fcbd-11e5-8684-fe587b626f7d.png)

But it still shows as 'new submission' in the project list in the Editor Dashboard
![image](https://cloud.githubusercontent.com/assets/15159847/14349898/0a693db6-fcbe-11e5-9ed9-e576d01a578b.png)

This should be updated to show that an action has been taken. I'm assuming that this is the case because the submission has not been sent into 'Editing' for peer review, but we need to indicate if pre-review revisions are being made. Could an option be to have a status anything that has been sent back to the author for revisions as 'Revisions Requested', regardless of whether peer-review has been conducted?

**Comment by IoannisCleary** [comment]
@twakeford  I can change the label to "in progress' when revisions have been requested however revisions can be requested at different stages of a submission. Or I can create a new label.

**Comment by ajrbyers** [comment]
@IoannisCleary Im handling this one.

**Comment by IoannisCleary** [comment]
preview
![ioijjoi](https://cloud.githubusercontent.com/assets/5523178/14464250/f16d5336-00c5-11e6-9785-d7f9b7e69274.png)
