### ISSUE TITLE
Copyediting rounds

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#377]
If an author returns their final copyedited file the editor can see the new file at the bottom of the right column for that Copyediting round
![image](https://cloud.githubusercontent.com/assets/15159847/14351991/35e20c82-fcca-11e5-880e-99cdaf4046c1.png)

If the editor wanted another round of copyediting then they can, by clicking 'Add copyeditor' again BUT, the most recent file from the author is not available to select (note the different file names). The most recent file is that previously submitted during the previous round of copyediting.

![image](https://cloud.githubusercontent.com/assets/15159847/14352042/6be757ec-fcca-11e5-9bd2-1b61e5495e0d.png)

As a work around, the editor can download and then upload the file, but a new round of copyediting should display the most recent version of the file.

**Comment by twakeford** [comment]
Ok - it does now seem to be working but is not 100% right.

When the author returns their file there is only an upload box:
![screen shot 2016-05-04 at 13 33 02](https://cloud.githubusercontent.com/assets/15159847/15014292/176addc2-11fd-11e6-9317-a99829c7b03b.png)
This means that a) the author can't upload multiple files and b) that they cannot add a label to the file.

Please could both a and b be addressed (in a new card?)

Addressing the original problem, if an editor does open a new round of copyediting then the author's file is now listed, but has now label/identifiable name to show which is most recent:
![screen shot 2016-05-04 at 13 34 28](https://cloud.githubusercontent.com/assets/15159847/15014340/57bc05f4-11fd-11e6-8c5b-85f707afd430.png)
Addressing the label should fix this (although should the copyeditor's file also be labelled as 'manuscript'?)

**Comment by IoannisCleary** [comment]
@twakeford the author can upload multiple files but i think labels cannot be edited

**Comment by twakeford** [comment]
ok - the author can upload multiple files but they need to know to hold the cmd key to select them.
![image](https://cloud.githubusercontent.com/assets/15159847/15044499/f446ee64-12cc-11e6-9a88-fc98d397014c.png)
We need to make this far more obvious that it is possible (edited books may have 10s of files to uploaded).
How come they can't be labelled? If the author can't label them themselves then we need to have a better way to describe them to the editor, as 'None' and 'Document 2' (see earlier screen shot) won't mean a lot to the other users

**Comment by IoannisCleary** [comment]
@twakeford  I updated the file upload to  the multiple file upload like other pages
![screenshot from 2016-05-05 16-24-31](https://cloud.githubusercontent.com/assets/5523178/15047717/07ea8f0a-12de-11e6-8b0b-05784e28bbb5.jpg)

**Comment by twakeford** [comment]
looks good!

**Comment by IoannisCleary** [comment]
@twakeford also updated the text below the buttons to match the page "When you have uploaded your files and are happy with their order, fill in any notes that you have gathered and then press the Complete Copyedit button to complete the review."

**Comment by twakeford** [comment]
Sounds good - thanks!
