### ISSUE TITLE
Sent to typesetting files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#379]
When sending files for typesetting the default list is 5 items long. There looks like there is an option to expand this list, however it doesn't do anything (see screenshot)

![image](https://cloud.githubusercontent.com/assets/15159847/14352396/38476b28-fccc-11e5-8d85-d9551a80de7e.png)

If it is possible to expand the list then that would be great. If not then the display needs to change to not suggest that it can.

**Comment by ajrbyers** [comment]
- [ ] Tweak datatable config to all 5, 10 & 20.

**Comment by twakeford** [comment]
I noticed that this was also a problem when looking at reviewer lists
