### ISSUE TITLE
Proposal details post acceptance

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#380]
Currently, I don't think that the completed proposal form is available after it has been accepted. The full email, review, event history needs to be available from the post-acceptance interface (detailed in other cards), but the actual proposal form also needs to be available.

Perhaps the Submissions Details page (or similarly relevant place) could include a link to the full proposal information and history?

**Comment by IoannisCleary** [comment]
Duplicate issue

**Comment by twakeford** [comment]
Could you let me know which is the original card that this duplicates?

**Comment by IoannisCleary** [comment]
@twakeford #306 
https://github.com/ubiquitypress/rua/issues/306
