### ISSUE TITLE
Proposal status

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#381]
The Proposal dashboard includes the column 'status' but this doesn't seem to reflect what is going on with the submission.
From the below, the status 'submission' doesn't give an indication of where the proposal is in the process. e.g. If the proposal is with reviewers then 'In Review' would make sense.
I think that if the author is revising the file then this is indicated, but the status should be higher resolution to help indicate if the editor needs to action anything.
![image](https://cloud.githubusercontent.com/assets/15159847/14500457/1fabce6a-019a-11e6-84f0-d26a2ca08864.png)

**Comment by IoannisCleary** [comment]
Preview of additional status options
![screenshot from 2016-04-14 15-18-21](https://cloud.githubusercontent.com/assets/5523178/14531170/3277eb4a-0254-11e6-882f-f0e78711895a.png)
