### ISSUE TITLE
Editorial Review

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#384]
When a user undertakes an Editorial Review, they should be in the Review app, not the Editor app.

- [x] Move views, urls and templates to the Review app
- [x] Ensure URL structure is similar to current

**Comment by twakeford** [comment]
@ajrbyers one thing that will probably get reported in my head on the Friday RUA review is that the Editorial review may need to be a separate set of settings than the 'normal' review. From the bit I saw this  afternoon, I realised that the Editorial Review would need a separate email template, instructions in the settings etc, as the task is going to be quite different. 

I can provide more detail on Friday, but thought that this may link to this issue so didn't want time wasted.

**Comment by ajrbyers** [comment]
Meant to add, did you move the models as well?
