### ISSUE TITLE
Current Status timeline error

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#389]
When a proposal is accepted and a full submission made then the timeline in the full submission 'Current Status' page has an error.
It starts by descending events, so the timeline moves down the page, with the most recent at the bottom (Proposal Submitted - Proposal Accepted - Submission)
BUT
Subsequent events are then tagged to the top of the timeline, so that the most recent is at the top (see below: Review)
![image](https://cloud.githubusercontent.com/assets/15159847/14567150/aee228fe-032a-11e6-94de-119429ad8291.png)

Please could you:
1. make it consistent, preferably with the most recent action at the top of the timeline/page
2. change 'Submission' to read 'Book Submitted' (to be consistent with 'Proposal Submitted')
3. if possible, also add the proposal review stage to show, if activated

**Comment by IoannisCleary** [comment]
@twakeford  timeline stages are not sorted. they are manually added (one by one)

**Comment by ajrbyers** [comment]
Should be able to add the date of the action and then sort based on that.

**Comment by twakeford** [comment]
yeah - if the list of events is not ordered then it could be too confusing.
The date is already shown, so what are they currently ordered by?
