### ISSUE TITLE
Contract process

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#391]
Currently the contract process/details are held only after full submission is complete, however, the contract will almost always be negotiated and signed during proposal (most proposals won't be accepted until a contract is signed)

= please can we moved/replicate the contract section into the proposal interface, which should then transfer into the submission details upon acceptance/full submission

**Comment by IoannisCleary** [comment]
@twakeford the submission page should display the contract but the contract pages/process should be moved to the proposals dashboard?

**Comment by twakeford** [comment]
Is it possible to have it on both? Th contract will be signed during the proposal, but if the book spec changes then a contract is occasionally updated. Having the proposal contract interface link to the same interface on the submission page would make sense.

I'm not sure if it is currently possible (haven't tested) but could we have version history available for contracts, and also the option to have multiple files in this section? This is because a contract is often updated as an addendum rather than a completely new full contract, so it doesn't technically add a new version of the contract, just an additional part to accompany it. (may be a different card)

**Comment by ajrbyers** [comment]
Hmmm. I think it is doable. We can simply have an FK to the proposal added. When a proposal is accepted, add an FK to the book so it is linked.

**Comment by twakeford** [comment]
What ever an FK is, it sounds good.
