### ISSUE TITLE
Editing published book data

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#392]
When books are published the book files/metadata are still available and editable (which will be useful) BUT, can we add a warning pop-up that alerts the user that their edits will directly effect the details that appear online and the files that are published?

As the pages will be available to press users that may not know the Production/publishing processes, I would like a safety net so that they cannot change something on a published book and not realise that it has quite big consequences.

**Comment by ajrbyers** [comment]
I hate pop-ups and can guarantee they will annoy production people. How about an alert at the top of the catalogue page that always displays?

**Comment by twakeford** [comment]
Production people won't be updating published content much, it is more to stop partner presses 'playing' around. An alert at the top of the page sounds ok though.

Is it only Press Editors that have access to the published data?

**Comment by IoannisCleary** [comment]
if the book is published this will appear
![screenshot from 2016-04-20 16-05-56](https://cloud.githubusercontent.com/assets/5523178/14679455/dfbf5ef2-0711-11e6-91b3-5e65cf79f2e0.png)

**Comment by twakeford** [comment]
Ace
