### ISSUE TITLE
Sender email details and reply-to address

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#393]
main@localhost.com is currently listed as the sender of a lot of the emails from RUA, this needs to be changed to something more appropriate to the publisher/user that sent the email:

1 - for auto emails, the sender should show as the publisher name, with a reply-to address that is the main contact for the publisher.

2 - for emails sent manually by a RUA user should ideally show as being sent from their name with a reply-to address that it their email address as per the user profile. A lot of the time the recipient will reply directly from the email rather than RUA. Although we want to try and avoid this, it is inevitable so needs to be made possible for the recipient to easily reply.

I realise that this is a long standing issue, so please let me know the alternatives if the above is not possible. Being clear who the emails are coming from will be important for the publisher (this is seen as urgent by current presses)

**Comment by ajrbyers** [comment]
We need to make a few changes to the way emails are sent with Rua, this means a large overhaul of the email systems.

- [ ] Move content rendering to its own function within email.py
- [ ] When a page has an email, we should display the rendered email using the new email.py function
- [ ] On POST, collect the edited version and email it
- [ ] Pass through REQUEST to email.send_email where possible
- [ ] Set the from address to be: "request.user.profile.full_name <press.from_address>"
- [ ] If request is passed through, set reply-to header = request.user.email

**Comment by ajrbyers** [comment]
Example function:

```
def get_email_content(request, context, template):

	try:
		template = models.Setting.objects.get(group__name='email', name=template).value
	except models.Setting.DoesNotExist:
		template = ''

	template = Template(template)
	con = RequestContext(request)
	con.push(context)
	html_content = template.render(con)

	return html_content
```

**Comment by IoannisCleary** [comment]
- [ ] Update editable email to text to rendered + use the get_email_content function
