### ISSUE TITLE
Attach file option needed on all emails

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#394]
There are some emails that a user can send where there is not an option to attach files. We need to add this to **all** user emails.

e.g. the invite reviewer email for the proposal stage currently does not allow the editor to attach a file

This needs to be applied to all current emails and any future ones that are added

**Comment by IoannisCleary** [comment]
@twakeford i added the attachment option to the proposal review pages. are there any pages in particular that need an attachment?

**Comment by twakeford** [comment]
Thanks - that was the only one that I noted
