### ISSUE TITLE
Review form option disappears for additional reviewer in proposal

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#395]
During proposal stage, when an editor invites the first reviewer they can choose from the available review forms:
![image](https://cloud.githubusercontent.com/assets/15159847/14580709/f4b65122-03cd-11e6-8a52-0e33e01296b1.png)

But if the editor then goes to invite another reviewer, via the +Add Reviewer button, then the option to choose the review form is not available:
![image](https://cloud.githubusercontent.com/assets/15159847/14580708/e296e916-03cd-11e6-9d96-f37c5477e37a.png)

= this needs correcting so that the same page is used with the same options.

**Comment by ajrbyers** [comment]
Do you want to allow setting different review forms for different reviewers?

We designed the specifically to avoid this as it's important all reviewers are prompted with the same questions.

**Comment by twakeford** [comment]
Yep, different review forms should be available - it is possible different sections of a book would require different criteria, but also SUP send the proposal to an Editorial Board to review and then an external reviewer, so they need to send two separate review forms.

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers so the proposal form needs to be linked to the proposal review model and not the proposal itself.

**Comment by ajrbyers** [comment]
@IoannisCleary @twakeford it would appear so, presumably this applies for normal review aswell Tim?

**Comment by twakeford** [comment]
That is correct.

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers I applied the update (models + views) but I will test it before I commit. This update will probably mean that any existing review assignments won't display correctly since the views will be looking for the review form of the assignment and not the submission.

**Comment by twakeford** [comment]
ok. If this can't be avoided then so be it, but please let me know when it is released, as there are live submissions in the review process now.

**Comment by ajrbyers** [comment]
@twakeford already avoided. It checks if there is a form a the proposal/book level and copies it over for those that don't have one.
