### ISSUE TITLE
Email log filter

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#396]
Book projects can have a lot of correspondence and being able to find previously discussed information is often required by searching through emails.

Can we therefore add the ability to search the content of the email logs and view associated conversations?

A possible additional useful feature would be the ability to tag/group emails (colour codes?) so that the user can have a system to group and easily recognise what the content of the emails refers to.

(*This is non-urgent and may need internal discussion to get the best option)

**Comment by IoannisCleary** [comment]
@twakeford I added search bars for both activity and email logs. Can you add the additional feature to a separate issue ?

**Comment by twakeford** [comment]
done

**Comment by IoannisCleary** [comment]
@twakeford Okay, thank you
