### ISSUE TITLE
New Reviewer return page

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#398]
When the +Add Reviewers option is selected during either the Proposal or full Submission review stage the the editor can add the new reviewer profile details but when it is saved the the page defaults to the general press user list. 

This needs to be changed so that the page defaults back to the page the the editor came from (either the proposal or submission review page)

**Comment by ajrbyers** [comment]
@IoannisCleary this should use the next=this/is/the/return/url stuff we've done previously:

- [ ] Add ?next=/url/here/ to the + Add Reviewers link
- [ ] Update the add user view to check for request.GET.get('next')
- [ ] If it exists, redirect the user to the next
- [ ] If not, do the normal redirect
