### ISSUE TITLE
Review feedback forms available to authors during revisions

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#400]
Currently authors can view the full, completed review form when being asked for revisions. We need to:

1 - make this an optional decision for the editor to make at the time of sending the request for revisions - it may not be a blanket rule for the author to see the whole form (reviewer could have been rude, editor may disagree with some of the comments etc)

2 - add button that allows the author to download the completed review forms as a text doc = the feedback is likely to be long and may be needed offline/away from RUA when the revisions are being made

*Note: this should be for proposals and full submission

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers  I'll add a hide button in the editor's review assignment page. when clicked the review is not shown to the author but still available to the editor. is that okay ?

**Comment by twakeford** [comment]
That sounds good to me. Just needs to be clear that if the option is selected then review is hidden. 

Thanks,

**Comment by IoannisCleary** [comment]
@twakeford I'll add the button as 'Hide from author'
