### ISSUE TITLE
completed proposal review doesn't transfer supporting files

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#402]
When a proposal reviewer attaches a supporting file it doesn't reach the editor

= need to make the file available to the editor and author (if the editor chooses - see #400)
![image](https://cloud.githubusercontent.com/assets/15159847/14589978/00d8bcaa-04e7-11e6-9b58-7b7554eaf35e.png)

**Comment by ajrbyers** [comment]
![screen shot 2016-04-21 at 12 00 30](https://cloud.githubusercontent.com/assets/8321378/14706794/ac75985c-07b8-11e6-871b-66879e6b560e.png)

Works, but the download button has a wierd font. Please fix.

**Comment by IoannisCleary** [comment]
@ajrbyers that's how the font looks on a btn-xs. the button was pushed to side when it was bigger and you could not see it

**Comment by ajrbyers** [comment]
@IoannisCleary Indeed, but this isn't our font. Im okay with the size, but the font needs to be the same as the rest of the site.

**Comment by IoannisCleary** [comment]
@ajrbyers i didn't change the font. do i need to add the btn-xs to the font in the css file?

**Comment by ajrbyers** [comment]
Yep.

**Comment by IoannisCleary** [comment]
@ajrbyers i added 'btn' to the lato font family. it looks like it worked. the font seems to change slightly
