### ISSUE TITLE
User Registration Bug & Design

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#404]
This relates to the public user registration page (e.g. http://sup.rua.pm/register/).

BUG: when a user registers they are not assigned a role. All new users should be auto assigned the role of an author. At the moment the Press Manager has to go into their profile to assign them a role after the registration has been completed. As they cannot log in until this is done, this is an **urgent** fix

**Comment by ajrbyers** [comment]
@twakeford blocked this into two issues.

**Comment by ajrbyers** [comment]
Closed as part of 5643960ff0dfa4b53abefee917bf16b43c6f16d2
