### ISSUE TITLE
New Registration Fields

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#405]
Registration doesn’t show all of the user profile options, only username, names, email and password = please can you amend the registration page to have all elements present. e.g. affiliation, social media handles, signature, biography, review interests etc. The only element to not give them is the option to sign up to more roles.

**Comment by IoannisCleary** [comment]
wrong issue added to commit message : 488edb71f0cd5f2a2537a43a0a0dfd73fd254c6a

**Comment by ajrbyers** [comment]
Reopening this. You need to render this form a field at a time and mix them in together. To be asked for your middlename and salutation after password makes little sense.

All you need to do is switch {% bootstrap_form form %} for a series of {% bootstrap_field form.field %} tags.

**Comment by ajrbyers** [comment]
@IoannisCleary reopening this issue. The interests field should be a TAGIT field.

**Comment by ajrbyers** [comment]
@IoannisCleary two things:

- [ ] Make interests field a TAGIT
- [ ] Layout the form like the profile edit page (can probably just copy it!!)
