### ISSUE TITLE
Email tagging/grouping

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#407]
Additional feature for email log: the ability to tag/group emails (colour codes?) so that the user can have a system to group and easily recognise what the content of the emails refers to.

(possibly like Trello colour tags that can be customised with labels)

**Comment by IoannisCleary** [comment]
@twakeford I added a kind variable to the email log similar to the log model. I also added a filter by feature. Now i will add colors for each filter type, is that okay?

**Comment by twakeford** [comment]
Not 100% sure what that all means. Any chance of a screen shot/demo?

**Comment by IoannisCleary** [comment]
@twakeford 
![screenshot from 2016-05-03 09-35-45](https://cloud.githubusercontent.com/assets/5523178/14978286/c35e53de-1112-11e6-9380-2c95b61e8452.png)
![screenshot from 2016-05-03 09-35-38](https://cloud.githubusercontent.com/assets/5523178/14978287/c3763bfc-1112-11e6-8262-6664c07772d6.png)
![screenshot from 2016-05-03 09-35-17](https://cloud.githubusercontent.com/assets/5523178/14978289/c38bbf54-1112-11e6-89c2-f1abd1175182.png)
![screenshot from 2016-05-03 09-35-08](https://cloud.githubusercontent.com/assets/5523178/14978288/c38a21da-1112-11e6-8487-751b1c0f42f8.png)

**Comment by twakeford** [comment]
I might need to see this in action before understanding fully.
What do the options in the drop down relate to/created by?
For example, if an author and editor are discussing copyright then this conversation could span a long time whilst the book continues to be processed. The email would therefore not directly relate to review, editing stages etc, but be more general. How would this fit?
It looks like a good start, but may not be flexible enough in the long term.

**Comment by IoannisCleary** [comment]
@twakeford they are automatic tags (proposal  emails get the 'proposal' tags except proposal review that gets 'proposal_reveiw' tag etc.). they can be used with the search function as well in order to limit the results further
