### ISSUE TITLE
Email subject lines

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#408]
Can we have the subject lines for emails editable via the press settings? As some emails will be in non-English, we will need to make the subject lines match the email content and to say what the press want them to. SUP have already asked for edits for the English versions so that they are clearer to the end user.

If allowing the press to customise the subject lines is not possible then we will have to review all of them, as a number of people have asked for them to be explained or edited already:
e.g. '[abp] Proposal Submission Ack' = what is [abp]? Can Ack be elongated to the full word?

(if you need motivation to find a way, then OMP does allow editable email subject lines ;-) )

**Comment by ajrbyers** [comment]
Before you do this one, we should have a chat. I have an idea for a new utility for fetching settings that will mean they don't break when it is missing.

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers one of the email subject text is added like this ''Submission decision update: %s' % decision_variable'. I assume the setting should only contain ''Submission decision update: "

**Comment by twakeford** [comment]
was a decision made if it will be possible for the subject lines to be edited by the presses via the settings?

**Comment by ajrbyers** [comment]
@twakeford ioannis is working on it now.

**Comment by IoannisCleary** [comment]
@twakeford I'm going through all the email functions and creating settings for each of them
