### ISSUE TITLE
General contact with press users

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#410]
We need to allow a method for more general communication between the assigned book editor that is handling a proposal or full submission and other users from the publisher and general public. Currently I think that this can only be done by assigning an extra editor to a submission or via the change user interface in proposals (currently broken, see #408).

There will often be times when someone will need to contribute something to a book project, but not need to be assigned to it (e.g. when a partner press contact an EM at UP asking for the BPC to be calculated).

I suggest that there is a general email option available in both the proposal and submission interfaces that allows assigned editors to contact other users with editor roles, as well as manually add email addresses to contact people outside of the user database. All of the outgoing emails should be recorded in the log (and if possible the incoming, although this doesn't sound possible).

**Comment by IoannisCleary** [comment]
@twakeford  you can add any email address you want on the email page. checking the bug right now

**Comment by twakeford** [comment]
which email page?

**Comment by ajrbyers** [comment]
@IoannisCleary we need a button added to proposal and submissions interfaces where it can open that popup with nothing pre-filled ok?

**Comment by IoannisCleary** [comment]
@ajrbyers @twakeford  should it enable search for people associated with the submission/proposal (while typing) or just an empty page?

**Comment by twakeford** [comment]
There should be an option to search for people with editor roles for the press (could also have all other roles but would be used less often). Then the option to manually add the send address

**Comment by IoannisCleary** [comment]
@twakeford the easiest thing to do would be just to enable search by name for all users on the website.

**Comment by twakeford** [comment]
that would be fine
