### ISSUE TITLE
New user emails

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#411]
Can we add a option on the editors' add user screens so that the editor can choose whether they are sent the email with their login details or not (defaulted to on)?

Editors may already be in conversation with these people and not want to double up on emails. Also, when adding them as a reviewer then they will receive an email shortly afterward which (hopefully) has a one-click URL, so again don't want to double up the number of emails and also they won't need the info if only acting as a reviewer.

**Comment by IoannisCleary** [comment]
@twakeford not sure about this. Will the editors send the login details to the  new users themselves ? What if they forget the login details before contacting the new user?

**Comment by twakeford** [comment]
In most cases it will be registration for a new reviewer, so 1-click URLs I think have now been agreed anyway.
I don't think that the editor passing on the details themselves will be a problem, and if they forget then they can always check the user list. If it is defaulted as on then that should cut out mistakes as the editor will have to consciously remove the default.

**Comment by IoannisCleary** [comment]
@twakeford It's always good to have a back up email of their login details in the case their details get lost or are forgotten @ajrbyers

**Comment by twakeford** [comment]
Who would have the back up? It would username/email would still be available to the editor and the user could do a password reset with their email address, if needed.
Sending reviewers 2 emails before they have accepted to do any work will just put them off = we need to find as many ways as possible to reduce any impact RUA has on them.

**Comment by IoannisCleary** [comment]
@twakeford I don't think this is necessary to do this because it's a one-off email, if you really want this feature I can add it. If the user resets the password they will still get an email with the reset code so the number of emails would be the same.

**Comment by twakeford** [comment]
I think it is needed. Once a press is up and running then the majority of times that the editor adds users will be for reviewers. If reviewers have 1 click urls then they don't need the log in details and sending the email is likely to be a negative impact. There is also the issue that the reviewers will have not had any contact with the  press in the past, so to send them login details without prior warning/communication may cause confusion. 
I do get your points, but it should be the editor that can decide.

**Comment by IoannisCleary** [comment]
@twakeford Okay I'll add it now
