### ISSUE TITLE
1-click reviewer option URLs

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#413]
We need to have a setting so that the Press can choose if they use 1-click reviewer URLs.

When enabled, reviewers should receive a URL in their email that leads directly into the review pages, with no username or password needed.

When 1-click is enabled, no other person should be cc'd or bcc'd into the email and the email log should not show the end URL. The end URL should also only display once the email reaches the reviewer, so that the editor only sees the key.

The setting should include text to alert the press to the fact that this makes data less secure, but it is ultimately their choice.

**Comment by IoannisCleary** [comment]
@twakeford @ajrbyers this will be probably require a second access key or use the existing access key field ?

**Comment by ajrbyers** [comment]
Use the existing one.

**Comment by IoannisCleary** [comment]
@ajrbyers Should i separate the views so that login is not required? Or remove the log in/is_reviewer decorator and if an access has not been used then i redirect them to the log in page

**Comment by ajrbyers** [comment]
You should be able to pop the access_key param out of request and check if it is valid for the current review inside the decorator.

**Comment by IoannisCleary** [comment]
@ajrbyers should i add a generate key check list option to the add reviewers/review assignment page? (generates uuid for each assignment) ?

**Comment by twakeford** [comment]
This has been re-opened as reviewer invitations from proposals are not 1-click links.

Either the above has been implemented but the key in the email needs updating, or the setting has not worked

**Comment by twakeford** [comment]
The above is also a problem for the full submission. An example review invitation that was sent this week had the URL http://up.rua.pm/review/external/31/assignment/8/decision/, which leads to the login page.

This is an urgent fix as requiring login will mean a far higher rejection/ignore rate from the reviewers. (it also changes the workflow for editors when registering new reviewer).

**Comment by twakeford** [comment]
Closed and transferred to https://trello.com/c/A2veAm5V/15-1-click-reviewer-access
