### ISSUE TITLE
Move Accept/Decline Buttons on Review and other pages

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#414]
![screen shot 2016-04-22 at 16 12 09](https://cloud.githubusercontent.com/assets/8321378/14745854/0e9cb2d0-08a5-11e6-8f70-db3dfab0d58d.png)

When Abstracts are long, the buttons disappear, so lets move them to under the DUE date on Reviews.

**Comment by IoannisCleary** [comment]
Buttons moved
![screenshot from 2016-04-22 16-17-26](https://cloud.githubusercontent.com/assets/5523178/14746077/d6e581c2-08a5-11e6-85cf-3619cc07b481.png)
