### ISSUE TITLE
Back button on version history

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#416]
The version history for submitted files currently doesn't have a back button = add one

**Comment by IoannisCleary** [comment]
@twakeford the version history can  be accessed by a lot of different pages (almost all pages with files) so you can't really know where to go. unless something can be done with ?next= ...

**Comment by ajrbyers** [comment]
@IoannisCleary @twakeford maybe it should open in a new tab?

**Comment by twakeford** [comment]
@IoannisCleary @ajrbyers doesnt the version page always lead from the list of files
e.g. http://template.rua.pm/editor/submission/7/
![image](https://cloud.githubusercontent.com/assets/15159847/14783068/3100810c-0ae5-11e6-8ec3-31441aca5741.png)

Can't a back button lead to where the version button is located (i.e. back to the list that was being looked at)?

**Comment by IoannisCleary** [comment]
@twakeford it can be accessed from the author or editor submission pages. in addition to production pages (chapter files)

**Comment by twakeford** [comment]
ok - it is very minor, so maybe not even worth doing anything about (back button on browser is available). A pop up doesn't seem to fit with any of the rest of RUA.

**Comment by IoannisCleary** [comment]
@twakeford i updated the button so that it opens up in a new tab so you can always just close the new tab

**Comment by twakeford** [comment]
ok - thanks
