### ISSUE TITLE
Proposal author communication with press

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#422]
Author of a proposal needs a method to communicate with the publisher = if editor has been assigned then the should have a direct email link; if no editor has been assigned then the author should be able to contact the main publisher email

**Comment by IoannisCleary** [comment]
@twakeford If an editor has been assigned to a proposal a pop up email section appears at the bottom with the editor's name. @ajrbyers is the publisher email the 'primary_contact_email' setting ?

**Comment by ajrbyers** [comment]
@IoannisCleary yes it is.
