### ISSUE TITLE
User role selection

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#425]
Make user roles easier to edit/select in Management.
The current interface requires the user to know that the cmd key (for Mac) is needed to select each role required. Users should not have to know to hold the key to select multiple roles, The current method also makes it hard to deselect a role without removing all of the other existing roles.

A far simpler interface would be that either each role does not need the key to be held to select and deselect (so they are all essentially independent), or make the list a list of tick boxes so that it is v easy and clear.

e.g. http://template.rua.pm/manager/user/5/edit/
![image](https://cloud.githubusercontent.com/assets/15159847/14768582/e72f74ea-0a3d-11e6-88f7-8bdbac012af4.png)

**Comment by IoannisCleary** [comment]
@twakeford an alternative solution is to try and remove the need of holding the cmd key. I found a javascript snippet that may do this. is that okay?

**Comment by twakeford** [comment]
sounds good
