### ISSUE TITLE
Display for submitted reviews

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#431]
Proposal & full submission screen for completed reviews display the review feedback as a narrow column on the right of the screen
proposal:
![image](https://cloud.githubusercontent.com/assets/15159847/14768816/6db20af0-0a43-11e6-9819-b856dbf32838.png)

full submission:
![image](https://cloud.githubusercontent.com/assets/15159847/14768845/c3befc78-0a43-11e6-81d6-23db21b5e379.png)

= as this text may be long and quite complex we need to display this in a more accessible way.

For the proposals, it would present the review better if the proposal form & instructions to the reviewer were not present = only the review details are on the screen, at full width. We can then add a link back to the review.

For the full submission, have the review feedback as the full width of the central and right column, so that it is easier to read the feedback. Access to the review rounds could be only on the main review landing page.

As this is quite a big change to the architecture of the page, please let me know if other display options are available.

**Comment by twakeford** [comment]
this also relates to #429 as it focuses on making the submitted reviews as accessible as possible.

**Comment by IoannisCleary** [comment]
@twakeford the updates seem to look okay. i added the necessary go back button to the review assignment and for proposal reviews i left the download of the proposal's details just in case
