### ISSUE TITLE
Editor dashboard filter

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#432]
The editor dashboard filter menu includes 'Urgency', but it is greyed out = either enable the feature or remove the option until available. (what is the thinking behind this feature?) 

![image](https://cloud.githubusercontent.com/assets/15159847/14769448/210e1bfa-0a50-11e6-8bec-b02dfcc20739.png)

**Comment by ajrbyers** [comment]
- [ ] Remove Urgency
