### ISSUE TITLE
Review Buttons

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#434]
![screen shot 2016-04-27 at 11 42 26](https://cloud.githubusercontent.com/assets/8321378/14849823/23a4622e-0c6d-11e6-9407-28d64b846a5d.png)

These buttons should all be on the same line.

**Comment by ajrbyers** [comment]
Delete, Withdraw, View and Hide that is :D

**Comment by IoannisCleary** [comment]
Updated button layout
![screenshot from 2016-04-27 13-31-34](https://cloud.githubusercontent.com/assets/5523178/14852197/c5cc1254-0c7c-11e6-98ba-f419be5072ff.png)
