### ISSUE TITLE
Editor dashboard filter

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#438]
Have default filter on editor dashboard as Book ID and add this option to the filter drop down menu

**Comment by IoannisCleary** [comment]
@twakeford the default filter is the empty filter that doesn't limit the number of books shown. How would the book id  work?

**Comment by ajrbyers** [comment]
Do you mean ORDER rather than FILTER?

**Comment by twakeford** [comment]
Ah yes - order all books by ID as default, not a filter at all (sorry, bad terminology used!)
