### ISSUE TITLE
Proposal error message

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#440]
When an author submits a proposal, after they press the submit button they still see a list of the form elements with a message saying that they are required fields. After a few seconds this disappears and the proposal is completed.

I know that this has been raised before, but still needs to be fixed as it doesn't look good.

**Comment by IoannisCleary** [comment]
@twakeford  for some reason the text area field is not causing the original errors. at least when i tested it now. so the error message appears as a reminder if the form has errors. need to test the update though ( just in case )

**Comment by IoannisCleary** [comment]
@twakeford i remember that it was an error with firefox. i'll test it now

**Comment by IoannisCleary** [comment]
@twakeford  seems to work on firefox

**Comment by twakeford** [comment]
I'm using Chrome, and it happened on there with the template journal

**Comment by IoannisCleary** [comment]
@twakeford not sure if latest commits to the repository change anything on template

**Comment by ajrbyers** [comment]
@IoannisCleary have you made changes for this issue?

**Comment by IoannisCleary** [comment]
@ajrbyers i pushed the commit but didnt notice it asked for login details again :p
