### ISSUE TITLE
Proposal author info

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#444]
We need to surface the registration info of the user to the proposal editor.

Part of the proposal review may involve knowing the author's affiliation, email address, social media so they should be able to preview the information that they have entered (obviously not password info)

(I thought that this had been ticketed before but I can't find it, so please let me know if this is a duplicate)

Alternatively, link more of the submitting author's info into the proposal form so that user data is already populated from their profile (and full profile available to the editor)

**Comment by IoannisCleary** [comment]
@twakeford We have a readonly profile page (does not have action buttons for editing the profile) that any user can access for any other user. Do you want the proposal author's name link to that page?

**Comment by twakeford** [comment]
@IoannisCleary yeah, sorry, I didn't realise that this was already implemented. I can now see that clicking on the user names shows their profile details. This will be fine.

**Comment by IoannisCleary** [comment]
@twakeford with proposal reviews you can't really link the submitting author/editor since they are not users / user fields and the proposal's owner/principal contact is not displayed.

**Comment by twakeford** [comment]
Sorry, bad terminology again - proposal review mentioned above related to the assessment by the Book Editor, not the external reviewer. The current button via the 'user' column in the proposal data is good, as it shows all available registration data for the submitting author.

**Comment by IoannisCleary** [comment]
@twakeford Okay so I'll close this issue
