### ISSUE TITLE
Proposal editor assignment

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#446]
1- When a Book Editor has been assigned to a proposal, this info needs to be surfaced a) in the Proposal Dashboard list and b) on the proposal page itself. I know that a user can already filter the proposal dashboard to only their own assignments, but the Press Editor may want an overview of each of their Book Editors

2 - when assigning a Book Editor to a proposal, is it possible to display how many active assignments they currently have? Adding a column next to their name would be useful (possibly 'Active assignments' and 'Completed assignments'?)

3 - when a Book Editor is assigned to a proposal they should:
a) receive an email (preferably editable prior to being sent) to notify them of their assignment and the details
b) from then on be the main contact for correspondence of the proposal = emails from the author side or reviewers should go to the assigned Book Editor and not the Press Editor/general contact

4 - When clicking the 'Book Editors' button on a proposal, please change the heading text on the resulting page from 'Add Book Editors' to 'Assign Book Editor(s)'
![image](https://cloud.githubusercontent.com/assets/15159847/15020600/9836780e-121a-11e6-93ef-68068ddd94c6.png)

**Comment by IoannisCleary** [comment]
@twakeford (2) By assignments do you mean any type of assignment (review, copyedit, index, typeset) ?

**Comment by IoannisCleary** [comment]
@twakeford i need a response soon so I can finish the issue today :stuck_out_tongue:

**Comment by twakeford** [comment]
I think only the number of proposals or books that they have been assigned as editors to. Other roles will mostly be other people so not directly relevant

**Comment by twakeford** [comment]
If it is possible to have a column to show how many proposals that they are assigned to and another column for how many full submissions they are assigned to, then that would be amazing. If easier, then combining these into 1 column that totals them is also good.
