### ISSUE TITLE
Proposal 'user'

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#447]
A proposal has a designated User, who is the principal contact for the author side of things. This is indicated in the top data bar of the proposal.
![image](https://cloud.githubusercontent.com/assets/15159847/15021239/97dae838-121d-11e6-93f0-18d7b0fe2135.png)

1 - please change the text in this column from 'User' to 'Principal Contact'

2 - when the 'change' button is clicked the page provided to assign a different user to the proposal still includes the intro text to the proposal form. This needs to be removed
![image](https://cloud.githubusercontent.com/assets/15159847/15021279/d1d76868-121d-11e6-9bf6-176e608a05d0.png)

3 - when the user/principal contact is changed then they will normally need to be notified. Could we therefore have an email box appear with a template text available that the editor can send. Could we also add a 'skip' button to this option, as they may have already corresponded with the person and not need the info repeating

4 - when a user/principal contact is changed then the page returns to the Proposals Dashboard. This should be changed so that it either stays on the same page, or defaults back to the proposal page

5 - when on the page to change a user, if the 'Back' button is pressed then it goes back to the Proposal Dashboard and not the page that the user came from (i.e. the proposal page)

**Comment by IoannisCleary** [comment]
@twakeford Can you send me an email template for the change of owner/principal contact setting ?

**Comment by twakeford** [comment]
Draft below (you will have to add the keys to add the required info:

Dear [user],

The book proposal, [_proposed book title_], that is in process with [press name] has been transferred into your name. This means that you are now the corresponding author/editor during the processing of this proposal. We will use this contact address to correspond with you regarding the review of the proposal and the ultimate editorial decision. We will be in touch once the next stages are complete.

As the corresponding author you will now be able to log into the book management system to view the proposal details, submit revisions and correspond with the assigned Book Editor. The proposal can be access via the below link (you should already have login details):

[proposal link]

Should you have received this email in error, please let us know as soon as possible.

Kind regards,
[user name]
[user signature]
