### ISSUE TITLE
Merge user function

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#487]
If a person registers multiple accounts then the editor could merge them so that associated submissions/tasks fall under one account. 

= 

1) editor selects the primary account
2) editor selects the secondary account
3) any empty profile data in the primary account is transferred from in the secondary account, if available (primary account data is kept if present)
4) tasks and submissions associated with the secondary account transfer to the primary account

(non-urgent)

**Comment by ajrbyers** [comment]
Removed from milestone.

**Comment by twakeford** [comment]
closed and added to Trello
