### ISSUE TITLE
Catalogue mandatory data: Table of contents

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#501]
The Catalog page will not allow the user to save changes to the metadata unless there is an entry in the Table of Contents section.
![image](https://cloud.githubusercontent.com/assets/15159847/16009483/cc8e2146-3174-11e6-8377-fc5e87859341.png)

This needs to be changes so that this is optional. The ToC data needs to be added upon publication, so will not necessarily be known by the editor whilst the submission is in process.

**Comment by twakeford** [comment]
test edit

**Comment by ajrbyers** [comment]
Fix has been added for this. To be rolled out. Moved to Release for 1.0.2 milestone where we can track completed items.
