### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#508]
Editors are not being notified when tasks are being completed. They need to receive emails when authors/reviewers/copyeditor/typesetters etc complete their tasks so that they can go back to RUA to check the action and progress the submission.

e.g. when the reviewer completes their review, or the author submits their revisions, the assigned book editor must get notified by email so that if they are not in RUA then they are alerted that action is needed.

**Comment by ajrbyers** [comment]
This isn't a bug, its an operational issue.

**Comment by twakeford** [comment]
I'm not saying it is a bug - I'm saying it needs actioning to fix/change
