### ISSUE TITLE
Optional Copyediting Workflow

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#70]
Model changes: copy_edit_file, copy_edit_assignments

- Button to start CE workflow
- Editor selects file to be copyediting (from all files associated with the submission)
- Copyeditor is invited to login and download the file
- Copyeditor completes and uploads the edited file
- Editor can invite Author to approve the copy edits
- Author uploads final manuscript

**Comment by pmackat** [comment]
change "Author can upload a file with comments" to "Author uploads final manuscript"

(i.e. we don't want them submitting more comments - at this stage, we want the manuscript text to be finalised and ready for typesetting)

**Comment by ajrbyers** [comment]
Done.
