### ISSUE TITLE
Optional Typsetting Workflow

### ISSUE THREAD

**Issue by ajrbyers** [ubiquitypress/rua#72]
Model changes: typeset_assignments, typeset_files

- Button to start typesetting
- Editor selects a file to be typeset
- Typesetter is invited to typeset the file
- Typesetter uploads the typeset media
- Author is invited to proof the media
- Author uploads proof feedback
- Typesetter is invited to view proof feedback
- Typesetter will make final edits and the upload the completed files

**Comment by pmackat** [comment]
after "Author is invited to proof the media"...
need to add steps:
"Author uploads proof feedback" 
"Typesetter is invited to view proof feedback"

**Comment by ajrbyers** [comment]
Done.
