### ISSUE TITLE
Add overview graph showing which stage books are at

### ISSUE THREAD

**Issue by tommowlam** [ubiquitypress/rua#76]
each stage is a column in a bar chart.

the bar chart varies in height depending on the number of books at that stage.

there is a deadline associated with each stage (and there is a tool to manage the deadlines).

the bar chart is a stacked chart - where a book is within deadline for the stage, it is green, where it is near the deadline or on the deadline it is amber, where the book is past the deadline, it is red.

clicking on the bar takes the user to a list of books at that particular stage.

the traffic light colour could be continued in the list of books at a stage (with a small coloured dot to the left, not with the whole row coloured).

when a book moves from one stage to another, then the chart is updated.

potentially: when a stage has been completed, it is tagged whether it was completed on time or not... then the progress timeline history, indicates this with the appropriate colour.

**Comment by ajrbyers** [comment]
I'm not so sure this has worked as well as we think it has in the journal platform @tommowlam... I think we should use the trello-like dashboard for this instead. Mark which stage each is in and display deadlines there.
